apps/docs/docs/introduction.md, apps/docs/docs/modules/index.md
=> patch various links

examples/storageContext.ts, packages/core/src/tests/StorageContext.test.ts
Added a test for the storage context, as well as an initial (broken) example that tries to load an index
=> initial storage examples attempt

apps/docs/docs/modules/low_level/storage.md
Small change to the storage example in the docs
=> fix storage example

.changeset/nasty-seas-care.md, apps/simple/notion.ts, apps/simple/package.json, packages/core/package.json, packages/core/src/index.ts, packages/core/src/readers/NotionReader.ts, packages/eslint-config-custom/index.js, pnpm-lock.yaml
Sorry for the large PR.
Once the basic functionality has been created, the PR is created.
Below are the TODOs for the future.
=> Add NotionReader

packages/core/src/Node.ts
I had a little difficulty dealing with `metadata`, so I made some modifications to make it type safe.
```ts
// before
const document = new Document({ text, metadata: { foo: "bar" }});
document.metadata.foo // any
// after
const document = new Document({ text, metadata: { foo: "bar" }});
document.metadata.foo // "bar"
```
=> Enhancing Type Safety for metadata

apps/docs/docs/introduction.md, apps/docs/docs/modules/high_level/data_loader.md, packages/core/package.json, packages/core/src/readers/DocxReader.ts, packages/core/src/readers/SimpleDirectoryReader.ts, pnpm-lock.yaml
- Added **`DocxReader`** - `packages/core/src/readers/DocxReader.ts`
- Modified **SimpleDirectoryReader** - `packages/core/src/readers/SimpleDirectoryReader.ts`
- Made changes to docs that show Data Loader support.
- `apps/docs/docs/modules/high_level/data_loader.md`
- `apps/docs/docs/introduction.md`
- Added package `mammoth`
=> Added DocxReader, adding support for reading .docx files.

apps/simple/portkey.ts, examples/portkey.ts, packages/core/package.json, packages/core/src/llm/LLM.ts, packages/core/src/llm/portkey.ts, pnpm-lock.yaml
This pull request introduces the Portkey integration to the LlamaIndexTS repository, enhancing its production capabilities. Portkey offers a comprehensive set of tools and features to optimize the performance and reliability of AI applications.
1. **🚪 AI Gateway**:
- **Automated Fallbacks & Retries**: Ensure your application remains functional even if a primary service fails.
- **Load Balancing**: Efficiently distribute incoming requests among multiple models.
- **Semantic Caching**: Reduce costs and latency by intelligently caching results.
2. **🔬 Observability**:
- **Logging**: Keep track of all requests for monitoring and debugging.
- **Requests Tracing**: Understand the journey of each request for optimization.
- **Custom Tags**: Segment and categorize requests for better insights.
3. …
=> feat: Portkey integration with LLamaIndexTS

packages/core/src/ChatEngine.ts, packages/core/src/ChatHistory.ts
Prevents context window overflow by including the messages from the ContextGenerator in the token calculation
=> Feature: Extract ContextGenerator and make HistoryChatEngine pluggable

apps/simple/vectorIndexCustomize.ts, packages/core/src/ChatEngine.ts, packages/core/src/QueryEngine.ts, packages/core/src/indices/BaseNodePostprocessor.ts, packages/core/src/indices/index.ts, packages/core/src/indices/keyword/KeywordTableIndex.ts, packages/core/src/indices/summary/SummaryIndex.ts, packages/core/src/indices/vectorStore/VectorStoreIndex.ts, pnpm-lock.yaml
I used the following as a guide to create SimilarityPostprocessor.
https://github.com/run-llama/llama_index/blob/72edf30c2c5c9765a0e714c6bb29197bdceae048/llama_index/indices/postprocessor/node.py#L62-L92
=> Add SimilarityPostprocessor

.gitignore, packages/core/package.json, packages/core/src/ChatEngine.ts, packages/core/src/callbacks/CallbackManager.ts, packages/core/src/llm/LLM.ts, pnpm-lock.yaml
Just for `HistoryChatEngine` (used by `chat-llamaindex`) and base LLM
=> Add support for GPT4 Vision Model

packages/create-llama/README.md
Small tweak to make the readme more informative
=> create-llama readme update

apps/docs/docs/end_to_end.md
Adds interactive Dev-Docs Tutorials.  Here is a  short loom video of how it works:
https://www.loom.com/share/41d7f1a00c0b461e89a89c9a3a3984b6?sid=98075458-ab63-48ab-9f01-c80b82bbf598
=> Add Interactive Tutorials Using Codespaces

packages/create-llama/README.md, packages/create-llama/index.ts
example run:
```
✔ What is your project named? … my-app
✔ Which template would you like to use? › Chat with streaming
✔ Which framework would you like to use? › NextJS
✔ Which UI would you like to use? › Just HTML
? Which chat engine would you like to use? › - Use arrow-keys. Return to submit.
❯  ContextChatEngine
SimpleChatEngine (no data, just chat)
```
=> fix: label for simple chat

packages/core/src/storage/vectorStore/PGVectorStore.ts
This commit fixes a mistake in query output mappings in the query method, and adds a specific check for empty embeddingResults in the add method.  This last change isn't a bug per se but in working on another vector store impl, I began to suspect that add is being called with an empty array when creating the service context (e.g., storageContextFromDefaults function).
=> Minor fixes in PGVectorStore

packages/core/src/storage/index.ts
=> Fix missing PGVectorStore export

packages/create-llama/create-app.ts, packages/create-llama/helpers/constant.ts, packages/create-llama/helpers/repo.ts, packages/create-llama/index.ts, packages/create-llama/questions.ts, packages/create-llama/templates/index.ts, packages/create-llama/templates/types.ts
- Added option to install templates from https://github.com/run-llama/create_llama_projects
- Simplified questions logic and used strong-typing for question args
To test:
```
pnpm build --filter create-llama
./packages/create-llama/dist/index.js 
```
=> Feat: Add support for installing templates from community repo

apps/docs/docs/end_to_end.md, examples/jsonExtract.ts
No changes to LITS are needed. Just an example of how to use it.
=> Feat: Added JSON extract example

.github/workflows/e2e.yml, packages/create-llama/templates/index.ts, packages/create-llama/templates/types/streaming/nextjs/package.json
Link issue: https://github.com/run-llama/LlamaIndexTS/issues/263
=> Fix: npm script does not run in window machine

packages/core/package.json, packages/core/src/Node.ts, pnpm-lock.yaml
https://nodejs.org/dist/latest-v18.x/docs/api/crypto.html#class-hash
=> refactor: remove unused deps

packages/core/src/nodeParsers/utils.ts, packages/core/src/tests/nodeParsers/SimpleNodeParser.test.ts
=> fix: add missing metadata after node parsing

packages/core/package.json, packages/core/src/TextSplitter.ts, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/363
=> fix(perf): use regex to spilt texts

packages/create-llama/templates/components/vectordbs/python/pg/constants.py, packages/create-llama/templates/components/vectordbs/python/pg/context.py, packages/create-llama/templates/components/vectordbs/python/pg/generate.py, packages/create-llama/templates/components/vectordbs/python/pg/index.py, packages/create-llama/templates/components/vectordbs/python/pg/utils.py, packages/create-llama/templates/python.ts
Following the TS version and the MongoDB codebase, I added the Postgres vector store component for FastAPI.
=> Feat: Add postgresql vector store for fastapi version

packages/core/package.json, packages/core/src/ChatEngine.ts, packages/core/src/GlobalsHelper.ts, packages/core/src/Node.ts, packages/core/src/QueryEngine.ts, packages/core/src/indices/BaseIndex.ts, pnpm-lock.yaml
Reduce bundle size and use web standards.
Ref: https://nodejs.org/docs/latest/api/crypto.html#cryptorandomuuidoptions
=> refactor: use `crypto.randomUUID`

examples/together-ai.ts, packages/core/src/embeddings/OpenAIEmbedding.ts, packages/core/src/embeddings/index.ts, packages/core/src/embeddings/together.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/index.ts, packages/core/src/llm/together.ts, packages/eslint-config-custom/index.js
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/367
=> feat: support Together AI

.changeset/moody-crabs-sniff.md, .changeset/new-forks-sin.md, .changeset/selfish-games-happen.md, packages/core/CHANGELOG.md, packages/core/package.json, packages/create-llama/CHANGELOG.md, packages/create-llama/package.json
Releases:
create-llama@0.0.14
llamaindex@0.0.45
[skip ci]
=> RELEASING: Releasing 2 package(s)

.changeset/mean-glasses-battle.md, packages/core/src/storage/kvStore/SimpleKVStore.ts
Closes: https://github.com/run-llama/LlamaIndexTS/pull/385
Change the output from `_.clone` to `_default.clone`
```js
class SimpleKVStore extends BaseKVStore {
put(key, val, collection = DEFAULT_COLLECTION) {
var _this = this;
return _async_to_generator$K(function*() {
if (!(collection in _this.data)) {
_this.data[collection] = {};
}
_this.data[collection][key] = ___default.clone(val); // Creating a shallow copy of the object
if (_this.persistPath) {
yield _this.persist(_this.persistPath, _this.fs);
}
})();
}
get(key, collection = DEFAULT_COLLECTION) {
var _this = this;
return _async_to_generator$K(function*() {
let collectionData = _this.data[collection];
if (___default.isNil(collectionData)) {
return null;
}
if (!(key in collectionData)) {
return null;
}
return …
```
=> fix: default import

.changeset/honest-months-add.md, packages/core/src/storage/kvStore/SimpleKVStore.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/382
Hope you can re-publish soon. Thank you for a great tool!
=> fix wrong import for lodash and path in SimpleKVStore.ts

examples/together-ai/vector-index.ts, packages/core/package.json
add more example https://github.com/run-llama/LlamaIndexTS/issues/367
=> feat: add together AI vector index example

packages/core/src/storage/vectorStore/ChromaVectorStore.ts
=> fix(getCollection): getOrCreateCollection

README.md
readme sample code is not runnable. So I updated.
=> readme sample code chnaged

.changeset/popular-grapes-cheat.md, .prettierignore, examples/chatEngine.ts, examples/keywordIndex.ts, examples/package.json, examples/sentenceWindow.ts, examples/storageContext.ts, examples/subquestion.ts, examples/summaryIndex.ts, examples/tsconfig.json, examples/vectorIndexCustomize.ts, packages/core/package.json, pnpm-lock.yaml, tsconfig.json
Separate from https://github.com/run-llama/LlamaIndexTS/pull/391
=> feat: use conditional exports

packages/core/src/GlobalsHelper.ts, packages/core/src/Node.ts, packages/core/src/QueryEngine.ts, packages/core/src/engines/chat/ContextChatEngine.ts, packages/core/src/engines/chat/DefaultContextGenerator.ts, packages/core/src/env/index.edge-light.ts, packages/core/src/env/index.ts, packages/core/src/indices/BaseIndex.ts, packages/core/src/llm/ollama.ts
split from: https://github.com/run-llama/LlamaIndexTS/pull/391
=> fix: abstract some node API

packages/core/src/embeddings/utils.ts, packages/core/src/env/index.edge-light.ts, packages/core/src/env/index.ts, packages/core/src/readers/CSVReader.ts, packages/core/src/readers/DocxReader.ts, packages/core/src/readers/HTMLReader.ts, packages/core/src/readers/ImageReader.ts, packages/core/src/readers/MarkdownReader.ts, packages/core/src/readers/PDFReader.ts, packages/core/src/readers/SimpleDirectoryReader.ts, packages/core/src/storage/FileSystem.ts, packages/core/src/storage/StorageContext.ts, packages/core/src/storage/constants.ts, packages/core/src/storage/docStore/SimpleDocumentStore.ts, packages/core/src/storage/indexStore/SimpleIndexStore.ts, packages/core/src/storage/kvStore/SimpleKVStore.ts, packages/core/src/storage/vectorStore/SimpleVectorStore.ts, packages/core/src/tests/GenericFileSystem.test.ts
import default file system from './env'
=> feat: abstract file system api

packages/core/package.json, packages/core/src/Node.ts, packages/core/src/env/index.edge-light.ts, packages/core/src/env/index.ts, packages/core/src/storage/StorageContext.ts, packages/core/src/storage/docStore/SimpleDocumentStore.ts, packages/core/src/storage/indexStore/SimpleIndexStore.ts, packages/core/src/storage/kvStore/SimpleKVStore.ts, packages/core/src/storage/vectorStore/SimpleVectorStore.ts, pnpm-lock.yaml
=> chore: abstract `node:path`

.changeset/famous-singers-shake.md, examples/vectorIndexEmbed3.ts, package.json, packages/core/package.json, packages/core/src/constants.ts, packages/core/src/embeddings/OpenAIEmbedding.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/azure.ts, packages/core/src/storage/vectorStore/PGVectorStore.ts, pnpm-lock.yaml
Also supporting the new GPT-4 preview model
=> Openai embeddings 3

examples/extractors/keywordExtractor.ts, examples/extractors/questionsAnsweredExtractor.ts, examples/extractors/summaryExtractor.ts, examples/extractors/titleExtractor.ts, packages/core/src/extractors/MetadataExtractors.ts, packages/core/src/tests/MetadataExtractors.test.ts
llm parameter should be optional (to be used with service context or defult openai) and being the first parameter doesn provide a good dev exp to use other parametrs
=> chore: enhancement optional args extractors

.changeset/silly-chefs-invent.md, packages/core/package.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/456
=> fix: output edge-light

apps/docs/docs/getting_started/concepts.md
https://ts.llamaindex.ai/getting_started/concepts have dead link, I fix it
=> docs: fix dead link

.changeset/proud-tigers-mix.md, README.md, examples/readers/load-pdf.ts, packages/core/package.json, packages/core/src/readers/PDFReader.ts, pnpm-lock.yaml
- smaller bundle size for PDF reader
`pdf2json` won't have extra dependencies like `canvas` (which will reach 150MB in nextjs serverless function), and split documents by pages instead of putting them into one document.
- faster parsing speed (6x - 10x faster)
- split documents by page, align with llama-index python
Fixes #394, #395
Demo: https://github.com/tuffstuff9/nextjs-pdf-parser
For, #394. I wrote a simple script, which will be faster by about 6-10x.
```shell
> node ./index.js
┌─────────┬──────────────┬─────────┬────────────────────┬───────────┬─────────┐
│ (index) │  Task Name   │ ops/sec │ Average Time (ns)  │  Margin   │ Samples │
├─────────┼──────────────┼─────────┼────────────────────┼───────────┼─────────┤
│    0    │  'pdf2json'  │   '6'   │ 164352966.60661697 │ '±65.55%' │ …
```
=> refactor: use `pdf2json` instead of `pdfjs-dist`

.changeset/warm-monkeys-check.md, packages/core/src/readers/SimpleDirectoryReader.ts
=> allow simpledirectoryreader to get a string

.changeset/honest-dragons-cough.md, packages/create-llama/helpers/index.ts, packages/create-llama/helpers/python.ts, packages/create-llama/helpers/types.ts, packages/create-llama/index.ts, packages/create-llama/questions.ts, packages/create-llama/templates/types/simple/fastapi/pyproject.toml, packages/create-llama/templates/types/streaming/fastapi/pyproject.toml
- Add a folder selection
- Update pdf selection into local file selection with the allowed file types are: [".pdf", ".doc", ".docx", ".ppt", ".pptx", ".csv"]
=> feat(create-llama) add folder selection & support more context data types

.changeset/unlucky-penguins-invent.md, packages/core/package.json
Upstream issue: https://github.com/huozhi/bunchee/issues/441
=> fix: instanceof issue

.changeset/smart-eels-design.md, packages/core/package.json, packages/core/src/indices/vectorStore/VectorIndexRetriever.ts, packages/core/src/indices/vectorStore/VectorStoreIndex.ts
...to VectorIndexRetriever constructor parameters.
=> fix: update `VectorIndexRetriever` constructor parameters' type.

packages/core/src/embeddings/OllamaEmbedding.ts, packages/core/src/embeddings/index.ts, packages/core/src/llm/ollama.ts
Related: https://github.com/run-llama/LlamaIndexTS/issues/293#issuecomment-1931311299
=> fix: add alias class OllamaEmbedding

.changeset/fuzzy-snails-applaud.md, packages/core/src/storage/vectorStore/PGVectorStore.ts
add implementation of metadata filter to PGVectorstore
=> feat: add filtering of metadata to PGVectorStore

.changeset/tame-ways-applaud.md, packages/core/src/embeddings/HuggingFaceEmbedding.ts, packages/core/src/embeddings/OpenAIEmbedding.ts, packages/core/src/embeddings/types.ts, packages/core/src/indices/vectorStore/VectorStoreIndex.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/483
=> feat: use batching in vector store index

apps/docs/docs/modules/llms/available_llms/azure.md, apps/docs/docs/modules/llms/available_llms/llama2.md, apps/docs/docs/modules/llms/available_llms/mistral.md, apps/docs/docs/modules/llms/available_llms/ollama.md, apps/docs/docs/modules/llms/available_llms/openai.md, apps/docs/docs/modules/llms/available_llms/portkey.md, apps/docs/docs/modules/llms/available_llms/together.md
fix some bugs in the examples and add the step to get the retriever, and makes the example of using ollama clearer
=> fix: some errors in available llms examples

.changeset/swift-waves-divide.md, README.md, apps/docs/docs/modules/llms/available_llms/groq.md, apps/docs/docs/modules/llms/available_llms/groq.mdx, examples/groq.ts, packages/core/src/llm/groq.ts, packages/core/src/llm/index.ts, packages/eslint-config-custom/index.js
Adds a LLM integration for Groq models.
Fixes # (issue)
=> feat: Add Groq LLM integration

apps/docs/docs/modules/evaluation/index.md, apps/docs/docusaurus.config.js, apps/docs/package.json, pnpm-lock.yaml
=> chore: fix paths and docs

examples/agent/multi_document_agent.ts
=> chore: remove storage context from multi_doc_agent example

packages/core/.cjs.swcrc
It seems like it's the same issue as https://github.com/TypeStrong/ts-node/issues/2035
Thanks help by @magic-akari
=> fix: keep dynamic import in cjs

.changeset/clean-camels-nail.md, examples/pinecone-vector-store/README.md, packages/core/src/storage/vectorStore/PineconeVectorStore.ts, packages/eslint-config-custom/index.js
- support for Pinecone namespaces #529
- lazy load pinecone store
- fix empty text response: #552
- may fix issue #564
=> feat: enhance pinecone usage

.changeset/eighty-ducks-beam.md, packages/core/src/agent/openai/base.ts
=> fix: prefix messages always true

.changeset/lucky-sheep-taste.md, .gitignore, packages/core/jsr.json, packages/core/src/cloud/utils.ts, packages/core/src/embeddings/fireworks.ts, packages/core/src/embeddings/together.ts, packages/core/src/llm/anthropic.ts, packages/core/src/llm/azure.ts, packages/core/src/llm/fireworks.ts, packages/core/src/llm/groq.ts, packages/core/src/llm/mistral.ts, packages/core/src/llm/open_ai.ts, packages/core/src/llm/portkey.ts, packages/core/src/llm/replicate_ai.ts, packages/core/src/llm/together.ts, packages/core/src/readers/AssemblyAIReader.ts, packages/core/src/readers/LlamaParseReader.ts, packages/core/src/storage/vectorStore/AstraDBVectorStore.ts, packages/core/src/storage/vectorStore/MongoDBAtlasVectorStore.ts, packages/core/src/storage/vectorStore/PineconeVectorStore.ts, packages/core/tests/tsconfig.json, packages/core/tsconfig.json, packages/env/jsr.json, packages/env/src/index.polyfill.ts, packages/env/src/index.ts, packages/env/src/type.ts, packages/env/src/utils.ts, packages/env/tsconfig.json, tsconfig.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/599
=> build: release to jsr

apps/docs/docs/modules/ingestion_pipeline/transformations.md
Fix typo in transformations.md
=> docs: Fix typo in transformations.md

.changeset/strange-ducks-kiss.md, examples/agent/react_agent.ts, packages/core/src/agent/react/formatter.ts, packages/edge/package.json
Updated react example to use Claude3.
To run:
```shell
cd examples
pnpm ts-node agent/react_agent.ts
```
=> feat: use claude3 with react agent

README.md
Fixes a few 404s and clarifies examples
=> fix: README links and examples

apps/docs/package.json, examples/package.json, pnpm-lock.yaml
=> fix: docs dependencies

packages/core/src/storage/vectorStore/PGVectorStore.ts
Spotted an issue that meant it wouldn't work and fixed it up.
=> Fixed postgres for "type"="module", ie es - should now work for both this and commonjs

examples/toolsStream.ts, packages/core/e2e/fixtures/llm/open_ai.ts, packages/core/src/agent/openai/worker.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/anthropic.ts, packages/core/src/llm/base.ts, packages/core/src/llm/mistral.ts, packages/core/src/llm/open_ai.ts, packages/core/src/llm/types.ts, packages/core/src/llm/utils.ts, packages/core/src/memory/ChatMemoryBuffer.ts, packages/core/src/memory/types.ts, packages/core/src/storage/chatStore/SimpleChatStore.ts, packages/core/src/storage/chatStore/types.ts, packages/core/tests/utility/mockOpenAI.ts
Step 2 of improving Agent
Related: https://github.com/run-llama/LlamaIndexTS/issues/692
=> refactor: chat message type

packages/core/e2e/node/snapshot/llm.snap, packages/core/src/llm/base.ts, packages/core/src/llm/ollama.ts, packages/core/src/llm/types.ts, packages/core/src/llm/utils.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/pull/704/files#r1558993933
=> fix: response.raw should be null

packages/core/e2e/fixtures/llm/anthropic.ts, packages/core/e2e/node/claude.e2e.ts, packages/core/e2e/node/openai.e2e.ts, packages/core/e2e/node/snapshot/llm-anthropic.snap, packages/core/e2e/node/utils.ts, packages/core/package.json, packages/core/src/llm/anthropic.ts, packages/edge/package.json, pnpm-lock.yaml
Upstream: https://github.com/run-llama/LlamaIndexTS/pull/691/files
=> feat: init claude function call (part 1)

.github/workflows/lint_on_push_or_pull.yml, apps/docs/docs/examples/agent.mdx, apps/docs/docs/modules/agent/multi_document_agent.mdx, apps/docs/docs/modules/agent/openai.mdx, apps/docs/docs/modules/agent/query_engine_tool.mdx, apps/docs/docs/modules/agent/react_agent.mdx
Upstream: https://github.com/run-llama/LlamaIndexTS/pull/694
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/724
=> docs: remove `verbose`

apps/docs/docs/modules/llms/available_llms/llama2.md
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/657
=> docs: fix example code

examples/llama3.ts, package.json, packages/core/src/llm/replicate_ai.ts, packages/core/src/llm/utils.ts, pnpm-lock.yaml
needed for create-llama examples
=> Add streaming for replicate (Llama 3)

packages/core/src/storage/vectorStore/AstraDBVectorStore.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19VOMtYYGUxl1N2kZp1j84bRqhEcZz7Y%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=oUgCmB9)
=> refactor: astra options

packages/core/e2e/fixtures/llm/open_ai.ts, packages/core/e2e/node/openai.e2e.ts, packages/core/e2e/node/snapshot/agent_with_object_function_call.snap, packages/core/e2e/node/snapshot/react-agent.snap, packages/core/src/agent/anthropic.ts, packages/core/src/agent/openai.ts, packages/core/src/agent/react.ts, packages/core/src/agent/utils.ts, packages/core/src/internal/utils.ts, packages/core/src/llm/open_ai.ts, packages/core/src/llm/types.ts, packages/core/src/tools/functionTool.ts, packages/core/src/types.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/740
=> feat: use json format for tool result

examples/agent/react_agent.ts, examples/agent/step_wise_react.ts, packages/core/e2e/node/react.e2e.ts, packages/core/src/agent/index.ts, packages/core/src/agent/react.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/pull/728#discussion_r1574121735
=> fix: rename ReACTAgent to ReActAgent

.husky/pre-commit, .husky/pre-push
remove running test before commit, because PR will check that
=> chore: update husky script

.changeset/angry-lizards-compete.md, packages/core/package.json, packages/core/src/internal/deps/ollama.d.ts, packages/core/src/internal/deps/ollama.js, packages/core/src/internal/deps/ollama.license, packages/core/src/llm/ollama.ts, pnpm-lock.yaml
Feedback from: https://discord.com/channels/1059199217496772688/1133167189860565033/1236027055317975110
=> fix: inline ollama build

.changeset/swift-beans-battle.md, packages/core/src/llm/openai.ts
TODO:
- support voice input for Agent?
=> feat: support gpt4-o

.changeset/afraid-seahorses-learn.md, examples/multimodal/context.ts, examples/multimodal/rag.ts, packages/core/src/engines/chat/ContextChatEngine.ts, packages/core/src/engines/chat/DefaultContextGenerator.ts, packages/core/src/synthesizers/MultiModalResponseSynthesizer.ts, packages/core/src/synthesizers/utils.ts
- adds support to use retrieved images in context chat engine
- adds example using it `examples/multimodal/context.ts`
- add streaming to multi modal response synthesizer
=> feat: use images in context chat engine

packages/core/e2e/node/openai.e2e.ts, packages/core/e2e/node/snapshot/agent.snap, packages/core/e2e/node/snapshot/agent_stream.snap, packages/core/e2e/node/snapshot/agent_with_object_function_call.snap, packages/core/e2e/node/snapshot/agent_with_object_retriever.snap, packages/core/e2e/node/snapshot/anthropic-agent-multiple-chat.snap, packages/core/e2e/node/snapshot/anthropic-agent.snap, packages/core/e2e/node/snapshot/gpt-4-turbo.snap, packages/core/e2e/node/snapshot/llm-anthropic.snap, packages/core/e2e/node/snapshot/openai_agent_system_prompt.snap, packages/core/e2e/node/snapshot/react-agent-stream.snap, packages/core/e2e/node/snapshot/react-agent.snap, packages/core/src/agent/anthropic.ts, packages/core/src/agent/openai.ts, packages/core/src/llm/anthropic.ts, packages/core/src/llm/openai.ts, packages/core/src/llm/types.ts
It was a pitfall, that openai could response multiple tool call in one response
=> fix: multiple tool call

.changeset/brown-elephants-switch.md, examples/groq.ts, packages/llamaindex/e2e/examples/nextjs-agent/package.json, packages/llamaindex/e2e/examples/nextjs-edge-runtime/package.json, packages/llamaindex/package.json, packages/llamaindex/src/llm/groq.ts, packages/llamaindex/src/llm/openai.ts, packages/llamaindex/src/next.ts, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/943
=> fix: groq llm

package.json
=> chore: fix new-version script

packages/env/src/index.workerd.ts, packages/env/src/tokenizers/node.ts, packages/env/tsconfig.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/957
=> fix: json import

.changeset/ten-hotels-shake.md, .github/workflows/publish.yml, packages/env/jsr.json, packages/llamaindex/e2e/examples/nextjs-node-runtime/package.json
JSR release, e2e package naming, CI name
=> chore: fix misc

.changeset/fuzzy-tigers-accept.md, apps/docs/docs/examples/agent_gemini.mdx, apps/docs/docs/modules/agent/index.md, examples/gemini/agent.ts, packages/llamaindex/src/agent/utils.ts, packages/llamaindex/src/llm/gemini/base.ts, packages/llamaindex/src/llm/gemini/types.ts, packages/llamaindex/src/llm/gemini/utils.ts, packages/llamaindex/src/llm/gemini/vertex.ts
=> feat: added Gemini tool calling support

.changeset/shiny-pants-change.md, packages/llamaindex/e2e/examples/nextjs-node-runtime/src/actions/openai.ts, packages/llamaindex/e2e/examples/nextjs-node-runtime/src/app/api/openai/route.ts, packages/llamaindex/src/next.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/992
=> fix: next.js binding

.changeset/cuddly-radios-fetch.md, packages/llamaindex/src/llm/anthropic.ts, packages/llamaindex/tests/llm/index.test.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/996
=> fix: anthropic image input

.github/workflows/preview.yml
https://github.com/stackblitz-labs/pkg.pr.new
Thanks @Aslemammad for this cool feature
=> ci: pre release

.github/workflows/lint_on_push_or_pull.yml, .github/workflows/preview.yml, .github/workflows/publish_github.yml, .github/workflows/release.yml, .github/workflows/test.yml
Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174
=> ci: fix setup pnpm

.changeset/loud-bananas-shout.md, packages/llamaindex/src/agent/react.ts
=> fix: corrected the regex in the react.ts file in extractToolUse & extractJsonStr functions

.changeset/lovely-flies-press.md, examples/multimodal/jina.ts, packages/llamaindex/src/embeddings/JinaAIEmbedding.ts, packages/llamaindex/src/index.ts
TS implement for Jina Embeddings through Jina API:
https://jina.ai/news/jina-clip-v1-a-truly-multimodal-embeddings-model-for-text-and-image/
Follow Python implement: 
https://github.com/run-llama/llama_index/blob/b17edc7c6800ba8c4f4c86e23ad57f2e3a0c3714/llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py#L38
=> feat: implement Jina embedding through Jina api

.changeset/shy-pots-marry.md, examples/readers/package.json, packages/llamaindex/src/readers/AssemblyAIReader.ts
- Update the AssemblyAI SDK to 4.6.0
- Add LlamaIndexTS to user agent which lets us attribute usage to LlamaIndexTS
=> fix: update user agent in AssemblyAI

.changeset/gentle-sloths-walk.md, packages/llamaindex/src/storage/vectorStore/PGVectorStore.ts, packages/llamaindex/src/storage/vectorStore/utils.ts
=> pgvectorstore support new conditions and operations

.changeset/funny-ants-do.md, examples/mongodb/2_load_and_index.ts, examples/mongodb/3_query.ts, examples/mongodb/README.md, packages/llamaindex/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
https://github.com/run-llama/LlamaIndexTS/issues/1135
=> feat: update mongodb vector store example

.changeset/loud-seas-run.md, packages/llamaindex/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
Removes unnecessary logging from MongoDB Atlas Vector store
=> chore: remove logging from mongodb atlas vector store

apps/docs/docs/introduction.md, apps/docs/docs/modules/chat_engine.md, apps/docs/docs/modules/data_index.md, apps/docs/docs/modules/embeddings/available_embeddings/mixedbreadai.md, apps/docs/docs/modules/evaluation/index.md, apps/docs/docs/modules/ingestion_pipeline/transformations.md, apps/docs/docs/modules/llms/available_llms/deepseek.md, apps/docs/docs/modules/node_postprocessors/mixedbreadiai_reranker.md, apps/docs/docs/modules/query_engines/index.md, apps/docs/docs/modules/retriever.md, packages/llamaindex/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
just fixed a few typos and added API references where possible
=> docs: fix typos, add API references

apps/docs/docs/guides/agents/2_create_agent.mdx
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1163
=> docs: fix example

.changeset/old-vans-melt.md, packages/core/src/workflow/events.ts, packages/core/src/workflow/workflow.ts, packages/core/tests/workflow.test.ts
=> feat: allow arbitrary types in workflow's StartEvent and StopEvent

.changeset/moody-feet-sit.md, .changeset/witty-windows-lick.md, packages/core/src/schema/node.ts, packages/env/src/global-check.ts, packages/env/src/index.browser.ts, packages/env/src/index.edge-light.ts, packages/env/src/index.ts, packages/env/src/utils/index.web.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1179
Similar issue: https://github.com/yjs/yjs/issues/438
=> fix: replace instanceof check with `.type` check

packages/cloud/turbo.json
Fixes: https://github.com/run-llama/LlamaIndexTS/actions/runs/10950567032/job/30406025700
=> chore: fix cache for cloud package

.changeset/cold-gifts-help.md, packages/core/src/memory/base.ts, packages/core/src/memory/chat-memory-buffer.ts, packages/core/src/memory/summary-memory.ts, packages/core/tests/memory/chat-memory-buffer.test.ts, packages/llamaindex/src/agent/base.ts, packages/llamaindex/src/engines/chat/CondenseQuestionChatEngine.ts, packages/llamaindex/src/engines/chat/ContextChatEngine.ts, packages/llamaindex/src/engines/chat/SimpleChatEngine.ts
=> fix: context not working in contextchatengine

.changeset/four-beers-kick.md, examples/agent/azure_dynamic_session.ts, examples/agent/stream_openai_agent.ts, examples/agent/wiki.ts, examples/anthropic/chat_interactive.ts, examples/chatEngine.ts, examples/chatHistory.ts, examples/cloud/chat.ts, examples/huggingface/embedding.ts, examples/huggingface/embeddingApi.ts, examples/multimodal/rag.ts, packages/autotool/examples/02_nextjs/actions.ts, packages/core/src/chat-engine/index.ts, packages/core/src/query-engine/base.ts, packages/llamaindex/e2e/examples/cloudflare-worker-agent/src/index.ts, packages/llamaindex/e2e/examples/nextjs-agent/src/actions/index.tsx, packages/llamaindex/e2e/node/openai.e2e.ts, packages/llamaindex/e2e/node/react.e2e.ts, packages/llamaindex/src/agent/anthropic.ts, packages/llamaindex/src/agent/base.ts, packages/llamaindex/src/engines/chat/CondenseQuestionChatEngine.ts, packages/llamaindex/src/engines/chat/ContextChatEngine.ts, packages/llamaindex/src/engines/chat/SimpleChatEngine.ts, packages/llamaindex/src/engines/query/RouterQueryEngine.ts, packages/llamaindex/src/evaluation/Faithfulness.ts
revert breaking API change. I think put in the first parameter is kind of standard of many npm library (like openai, anthropic)
=> revert: stream back to first parameter

apps/docs/docs/modules/data_loaders/llama_parse/index.mdx
Commit 85c2e198a4a76b81e19754bd683d5d6db1725ea6 moved and renamed the `LlamaParseReader.ts` to be `reader.ts`. This Pr adjusts sources to changes.
=> fix: update reader reference

.changeset/breezy-donkeys-buy.md, packages/llamaindex/src/vector-store/PineconeVectorStore.ts
Based on Python filters:
https://github.com/run-llama/llama_index/blob/a620a2661faabb49ba2f257bff7ae2ac04d0c12b/llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py#L132-L162
=> feat: add filters for pinecone

packages/llamaindex/src/indices/vectorStore/index.ts, packages/llamaindex/src/storage/StorageContext.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1277
=> fix: bypass service context embed model

.changeset/real-ears-design.md, packages/cloud/src/reader.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1283
=> fix(cloud): llama parse reader save image incorrectly

.changeset/proud-mayflies-worry.md, packages/cloud/package.json, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1274
=> fix(cloud): package.json format

.changeset/afraid-pots-raise.md, examples/agent/large_toolcall_with_gpt4o.ts, packages/llamaindex/src/Settings.ts, packages/llamaindex/src/embeddings/fireworks.ts, packages/llamaindex/src/embeddings/together.ts, packages/llamaindex/src/index.edge.ts, packages/llamaindex/src/llm/deepinfra.ts, packages/llamaindex/src/llm/deepseek.ts, packages/llamaindex/src/llm/fireworks.ts, packages/llamaindex/src/llm/together.ts, packages/llamaindex/tests/init.test.ts, packages/llm/groq/src/llm.ts, packages/llm/openai/src/azure.ts, packages/llm/openai/src/embedding.ts, packages/llm/openai/src/index.ts, packages/llm/openai/src/llm.ts
feedback from Okta. Now we set Settings.llm to OpenAI by default and lazy loading the OpenAI
=> fix: lazy load openai

.changeset/gold-jokes-deny.md, packages/core/src/indices/prompt-helper.ts, packages/core/src/node-parser/index.ts, packages/core/src/node-parser/token-text-splitter.ts, packages/core/src/node-parser/utils.ts, packages/core/src/prompts/prompt.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1296
=> fix: num output incorrect in prompt helper

.changeset/soft-papayas-care.md, examples/chromadb/preFilters.ts, packages/llamaindex/package.json, packages/llamaindex/src/next.ts, packages/llamaindex/src/vector-store/ChromaVectorStore.ts, pnpm-lock.yaml
Based on Python implement:
https://github.com/run-llama/llama_index/blob/a0bc834321b718c52ab449957abcb3afa7a4b548/llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py#L59
=> feat: ChromaDb metadata filters

examples/vectorIndexFromVectorStore.ts, packages/llamaindex/src/indices/vectorStore/index.ts, packages/llamaindex/src/ingestion/IngestionPipeline.ts, packages/llamaindex/src/ingestion/strategies/UpsertsAndDeleteStrategy.ts, packages/llamaindex/src/ingestion/strategies/UpsertsStrategy.ts, packages/llamaindex/src/ingestion/strategies/index.ts, packages/llamaindex/src/storage/StorageContext.ts, packages/llamaindex/src/vector-store/AstraDBVectorStore.ts, packages/llamaindex/src/vector-store/ChromaVectorStore.ts, packages/llamaindex/src/vector-store/MilvusVectorStore.ts, packages/llamaindex/src/vector-store/MongoDBAtlasVectorStore.ts, packages/llamaindex/src/vector-store/PGVectorStore.ts, packages/llamaindex/src/vector-store/PineconeVectorStore.ts, packages/llamaindex/src/vector-store/QdrantVectorStore.ts, packages/llamaindex/src/vector-store/SimpleVectorStore.ts, packages/llamaindex/src/vector-store/UpstashVectorStore.ts, packages/llamaindex/src/vector-store/WeaviateVectorStore.ts, packages/llamaindex/src/vector-store/types.ts, packages/llamaindex/tests/vector-stores/SimpleVectorStore.test.ts
Close: https://github.com/run-llama/LlamaIndexTS/pull/1191
=> fix: vector store type

packages/llamaindex/e2e/node/vector-store/pg-vector-store.e2e.ts, packages/llamaindex/src/vector-store/PGVectorStore.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1314
=> fix(pg): allow passing perform setup

.changeset/early-kings-flash.md, packages/env/package.json, packages/env/src/fs/memory.ts, packages/env/src/index.browser.ts, packages/env/src/index.edge-light.ts, packages/env/src/node-polyfill.ts, packages/env/src/url/index.ts, packages/env/src/web-polyfill.ts, packages/llamaindex/package.json, pnpm-lock.yaml
Inconstant API in different might cause build error when using esbuild, vite or rollup.
=> fix(env): align export APIs

.changeset/metal-worms-decide.md, package.json, packages/core/package.json, packages/core/src/prompts/base.ts, packages/core/src/prompts/format.ts, pnpm-lock.yaml
copy prompt function from npm and remove Object.defineProperty in case of HMR issue in webpack/vite
=> fix(core): inline `python-format-js`

.changeset/calm-pandas-battle.md, .vscode/settings.json, packages/llamaindex/src/indices/vectorStore/index.ts
=> fix: VectorIndexRetrieverOptions typing

.changeset/famous-kings-develop.md, packages/env/src/index.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1127#issuecomment-2435243772
magic string
=> fix(env): no esm shim

apps/next/src/app/(home)/page.tsx, apps/next/src/components/magic-move.tsx, apps/next/src/components/ui/skeleton.tsx
Related: https://github.com/fuma-nama/fumadocs/issues/983
=> docs(next): fix shiki theme

.changeset/shaggy-houses-breathe.md, apps/next/src/actions/index.tsx, packages/core/src/agent/base.ts, packages/core/src/chat-engine/base.ts, packages/core/src/chat-engine/context-chat-engine.ts, packages/core/src/chat-engine/default-context-generator.ts, packages/core/src/chat-engine/index.ts, packages/core/src/chat-engine/simple-chat-engine.ts, packages/core/src/chat-engine/type.ts, packages/llamaindex/src/engines/chat/index.ts
Related: https://github.com/run-llama/LlamaIndexTS/issues/1399
=> refactor(core): move `ContextChatEngine` and `SimpleChatEngine`

.changeset/tall-badgers-melt.md, packages/core/src/global/settings/chunk-size.ts, packages/core/src/global/settings/llm.ts, packages/core/src/global/settings/tokenizer.ts, pnpm-lock.yaml, unit/package.json, unit/settings/global.test.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1359
=> fix(core): async local storage in `Setting.with` API

packages/cloud/package.json
We have a report that someone have issue using pnpx (I think because pnpm version is still 8.x)
=> fix: remove usage of pnpx

.changeset/cuddly-bugs-train.md, packages/llamaindex/src/postprocessors/rerankers/CohereRerank.ts
add options for cohere for proxy and timeout
=> feat: add baseUrl and timeout option in cohere rerank

CONTRIBUTING.md, apps/next/README.md, apps/next/turbo.json
=> docs: update `CONTRIBUTING.md`

.changeset/short-candles-drive.md, e2e/fixtures/llm/ollama.ts, e2e/node/ollama.e2e.ts, e2e/node/snapshot/ollama.snap, packages/core/src/llms/base.ts, packages/llamaindex/src/embeddings/OllamaEmbedding.ts, packages/providers/ollama/src/index.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1430
=> feat: support ollama tool call

.changeset/pink-dolls-destroy.md, examples/vllm.ts, packages/llamaindex/package.json, packages/llamaindex/src/llm/index.ts, packages/providers/vllm/package.json, packages/providers/vllm/src/index.ts, packages/providers/vllm/src/llm.ts, packages/providers/vllm/tsconfig.json, pnpm-lock.yaml, tsconfig.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1379
=> feat: vllm support

.changeset/soft-tools-wonder.md, packages/core/src/memory/base.ts, packages/core/src/memory/chat-memory-buffer.ts, packages/core/src/storage/chat-store/base-chat-store.ts, packages/core/tests/memory/chat-memory-buffer.test.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1469
=> feat: async get message on chat store

.changeset/honest-moose-roll-2.md, .changeset/honest-moose-roll.md, examples/anthropic/prompt-caching.ts, packages/core/src/llms/base.ts, packages/providers/anthropic/package.json, packages/providers/anthropic/src/llm.ts, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1487
=> feat(anthropic): support prompt caching

.changeset/swift-dodos-develop.md, packages/llamaindex/src/storage/chatStore/AzureCosmosNoSqlChatStore.ts, packages/llamaindex/src/storage/index.ts
This PR adds the functionality to use Azure Cosmos DB as a chat store.
=> feat: add Azure CosmosDB NoSql Chat store

.changeset/olive-bobcats-check.md, packages/llamaindex/src/storage/kvStore/AzureCosmosNoSqlKVStore.ts, packages/llamaindex/src/vector-store/AzureCosmosDBNoSqlVectorStore.ts
Update user-agent-suffix for CosmosDB
Fix typo
=> chore: update azure cosmos db

.changeset/cyan-dingos-compare.md, packages/readers/package.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1497
=> fix: import error in cjs

packages/llamaindex/src/readers/index.ts, packages/readers/obsidian/package.json
make it accessable in reader index
=> fix: add obsidian reader to index

.changeset/hip-windows-tease.md, apps/next/src/content/docs/llamaindex/integration/vercel.mdx, examples/vercel/README.md, examples/vercel/llamacloud.ts, examples/vercel/llm.ts, examples/vercel/vector-store.ts, packages/providers/vercel/src/index.ts, packages/providers/vercel/src/llm.ts, packages/providers/vercel/src/tool.ts
=> Add adapter to use Vercel model providers

packages/cloud/package.json, packages/core/package.json, packages/env/package.json
Related: https://github.com/run-llama/LlamaIndexTS/issues/1623
Upstream: https://github.com/huozhi/bunchee/issues/656
=> fix: bundler issue default in default

e2e/node/smoke.e2e.ts
I believe there shouldn't have require ESM issue?
=> test: add cjs smoke test

.changeset/eleven-plums-prove.md, packages/cloud/openapi.json, packages/cloud/src/reader.ts
Use latest openapi.json from: https://api.cloud.llamaindex.ai/api/openapi.json
=> chore: bump llamacloud openapi

.changeset/afraid-boxes-approve.md, examples/chat-engine/streaming.ts, packages/core/src/agent/base.ts, packages/core/tests/agents.test.ts
Streaming is not working with LLMAgent. To reproduce, run this example:
```
npx tsx chat-engine/streaming.ts
```
https://github.com/user-attachments/assets/f50525f6-8d22-44c6-8603-1881efe70e17
=> fix: streaming issues with LLMAgent

.changeset/orange-ducks-pull.md, apps/next/src/content/docs/llamaindex/getting_started/setup/node.mdx, examples/package.json, packages/env/package.json, packages/env/src/internal/tokenizers/node.ts, packages/experimental/package.json, packages/llamaindex/package.json, pnpm-lock.yaml
In Next.js, this page should build successfully in Edge Runtime:
```
import "llamaindex";
export const runtime = "edge";
export default function Home() {
return <div>Next.js Edge Runtime</div>;
}
```
=> fix: build fail in edge runtime

apps/next/src/app/(home)/page.tsx, apps/next/src/app/docs/layout.tsx, apps/next/src/app/layout.tsx, apps/next/src/components/ai-chat.tsx, apps/next/src/components/contribution.tsx, apps/next/src/components/contributor-count.tsx, apps/next/src/components/create-app-animation.tsx, apps/next/src/components/demo/code-node-parser.tsx, apps/next/src/components/demo/workflow-streaming-ui.tsx, apps/next/src/components/feature.tsx, apps/next/src/components/flow-input.tsx, apps/next/src/components/message.tsx, apps/next/src/components/npm-install.tsx, apps/next/src/components/reactbits/rotating-text.tsx, apps/next/src/components/ui/dialog.tsx, apps/next/src/components/ui/input.tsx, apps/next/src/components/ui/skeleton.tsx, apps/next/src/components/ui/slider.tsx, apps/next/src/components/ui/textarea.tsx, apps/next/src/components/ui/tooltip.tsx, e2e/examples/waku-query-engine/src/components/chat.tsx, package.json, pnpm-lock.yaml, prettier.config.mjs
tailwind eslint plugin is block by upstream: https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/325
=> chore: add tailwindcss prettier

.changeset/shiny-camels-deny.md, apps/next/src/content/docs/llamaindex/modules/workflows.mdx, examples/agentworkflow/multiple_agents.ts, examples/agentworkflow/single_agent.ts, examples/node/workflow/basic.ts, examples/workflow/app-creator.ts, examples/workflow/conditional.ts, examples/workflow/joke.ts, examples/workflow/stream-events.ts, examples/workflow/timeout.ts, examples/workflow/validation.ts, packages/llamaindex/src/index.edge.ts, packages/workflow/src/agent/agent-workflow.ts, packages/workflow/src/agent/function-agent.ts, unit/workflow/workflow-ui.test.tsx, unit/workflow/workflow.test.ts
=> feat: make AgentWorkflow llm param optional

.changeset/calm-windows-fry.md, packages/providers/storage/azure/src/vectorStore/AzureCosmosDBMongoVectorStore.ts
Add UA in order to track the usage of AzureCosmosDBMongoDBVectorStore
=> fix: Add user agent for AzureCosmosDBMongoDBVectorStore

.changeset/tricky-seals-smoke.md, apps/next/src/content/docs/llamaindex/modules/llms/available_llms/perplexity.mdx
Added documentation for using perplexity llm
=> docs: add doc for perplexity

.changeset/hungry-turkeys-wait.md, apps/next/src/content/docs/llamaindex/modules/llms/available_llms/openai.mdx, packages/providers/openai/src/embedding.ts, packages/providers/openai/src/llm.ts
Makes it possible to use the OpenAI provider with OpenAI-compatible APIs like Scaleway Generative APIs.
=> feat: make it possible to provide base URL to OpenAI

.changeset/heavy-ants-turn.md, packages/providers/google/src/base.ts, packages/providers/google/src/vertex.ts
Fixes https://github.com/run-llama/LlamaIndexTS/issues/1573
=> chore: added saftey setting as parameter for gemini

.changeset/early-singers-look.md, packages/providers/google/src/studio/utils.ts
=> fix: include inline data check for GoogleStudio

.changeset/yellow-walls-happen.md, packages/workflow/src/agent/agent-workflow.ts, packages/workflow/test/agent-workflow.test.ts
Fix: [1766](https://github.com/run-llama/LlamaIndexTS/issues/1766)
=> Fix wrong multi-agent setup

.changeset/wise-goats-scream.md, packages/providers/storage/mongodb/package.json, packages/providers/storage/mongodb/src/docStore/MongoDBDocumentStore.ts, packages/providers/storage/mongodb/src/index.ts, packages/providers/storage/mongodb/src/kvStore/MongoKVStore.ts, packages/providers/storage/mongodb/src/tests/MongoDocumentStore.test.ts, packages/providers/storage/mongodb/src/tests/MongokVStore.test.ts, packages/providers/storage/mongodb/src/tests/setuptTestDb.ts, pnpm-lock.yaml
Fixes https://github.com/run-llama/LlamaIndexTS/issues/136
=> feat: add support for mongodb document store

.changeset/curly-brooms-sip.md, examples/package.json, examples/vector-store/elastic-search/index.ts, examples/vector-store/elastic-search/package.json, packages/providers/storage/elastic-search/package.json, packages/providers/storage/elastic-search/src/ElasticSearchVector.ts, packages/providers/storage/elastic-search/src/ElasticSearchVectore.ts, packages/providers/storage/elastic-search/src/index.ts, packages/providers/storage/elastic-search/src/utils.ts, packages/providers/storage/elastic-search/tests/ElasticSearchVectorStore.test.ts, packages/providers/storage/elastic-search/tsconfig.json, pnpm-lock.yaml, tsconfig.json
Fixes https://github.com/run-llama/LlamaIndexTS/issues/818
=> feat: elastic search vector store

.changeset/mighty-ducks-tell.md, apps/next/src/content/docs/llamaindex/modules/ui/llamaindex-server.mdx, packages/server/src/server.ts, packages/server/src/types.ts
```
new LlamaIndexServer({
workflow: workflowFactory,
uiConfig: {
appTitle: "LlamaIndex App",
componentsDir: "components",
starterQuestions: ["What is the LlamaIndex?"],
llamaCloudIndexSelector: true,
},
}).start();
```
=> feat: enhance config params for LlamaIndexServer

apps/next/src/app/docs/layout.tsx
The little chat feature was fake and kind of confusing for users.
Lets just remove it until we implement an actual chat feature
=> remove fake chat

package.json, packages/cloud/package.json, pnpm-lock.yaml
Keep same with https://github.com/run-llama/llama-flow/blob/main/package.json#L6 to make sure our cross-repo CI is aligned
=> chore: bump pnpm

apps/next/source.config.ts
fix: https://github.com/run-llama/LlamaIndexTS/issues/1870
=> fix: The search function on the documentation site is not working.

apps/next/package.json, apps/next/scripts/generate-docs.mts, apps/next/scripts/validate-links.mts, apps/next/typedoc.json, pnpm-lock.yaml
=> make docs great again - 2nd time

.changeset/brown-roses-smash.md, packages/workflow/package.json, packages/workflow/src/agent/agent-workflow.ts, packages/workflow/src/index.ts, pnpm-lock.yaml
=> chore: update @llama-flow/core to version 0.4.1 and export stream api

.changeset/silver-sloths-tickle.md, packages/workflow/src/agent/agent-workflow.ts, packages/workflow/test/agent-workflow.test.ts
fix: #1923 
It seems like all that needed to be done was to change the input interface.
=> feat: update agent input interface to support files

packages/providers/anthropic/src/llm.ts
Need to check for `-4`
When claude-2 gets retired, we can just make this always return true
=> improve funcion call check in anthropic llm

.changeset/six-adults-battle.md, packages/workflow/package.json, pnpm-lock.yaml
Update to latest [@llama-flow/core](https://github.com/run-llama/llama-flow) package
- Fixes [#1978](https://github.com/run-llama/LlamaIndexTS/issues/1978)
- Tested against a test case similar to [#110](https://github.com/run-llama/llama-flow/pull/110)
- If this is usually done in any automated process, please feel free to close this PR.
- Feel free to comment if I need to add test cases like in [#110](https://github.com/run-llama/llama-flow/pull/110)
=> chore: Bump @llama-flow/core package version

apps/next/CLAUDE.md, apps/next/next.config.mjs, apps/next/package.json, apps/next/scripts/validate-links.mts, apps/next/source.config.ts, apps/next/src/content/docs/llamaindex/modules/agents/workflows.mdx, apps/next/src/content/docs/meta.json, apps/next/turbo.json, pnpm-lock.yaml
Updating docs to properly link to latest workflow docs
Sister PR: https://github.com/run-llama/workflows-ts/pull/118
=> Rename llama-flow -> workflows in docs

apps/next/package.json, apps/next/src/app/layout.tsx, apps/next/src/content/docs/llamaindex/modules/data/memory/index.mdx, pnpm-lock.yaml
Adding our google analytics tag to the root layout of the docs
=> add google analytics

.changeset/ripe-trains-camp.md, packages/tools/package.json, packages/tools/src/tools/interpreter.ts, pnpm-lock.yaml
This helps reduce effort on tuning prompt to guide LLM specify files to be uploaded.
=> update interpreter to always upload all files in the configured directory

CONTRIBUTING.md
=> fix: adding more details in the contribution guidelines about changesets

.changeset/eleven-masks-bow.md, packages/cloud/src/beta/agent/types.ts
See related change for py here: https://github.com/run-llama/llama_cloud_services/pull/815
=> Adding support for page citations, and refactor the confidence into the field metadata

.changeset/strong-cheetahs-mate.md, packages/providers/google/src/base.ts
=> #2159 Remove unneeded console logs from gemini stream
