run-llama/LlamaIndexTS

packages/core/src/indices/vectorStore/VectorStoreIndex.ts
Use `retriever` from argument if it exists.
Just a brief bug fix. I noticed you take `retriever` as argument of asQueryEngine function but always use `this.asRetriever()` despite you declaring retriever as `retriever ?? this.asRetriever();`. I think it is a mistake.
So use `retriever` if it exists.
- c06d1e5b0930de9f84b43b21b0be4c06552ac727 Use `retriever` as argument of RetrieverQueryEngine if it exists. The current behavior is always using `this.asRetriever()` and just ignoring `retriever` despite declaring it.
- 34f5398f41109758a655bc1c1adbe67ddb5a26f4 Brief refactoring. Integrate module importations from `BaseIndex` to one declaration.
=> [BUG FIX] Use retriever from argument if exist in asQueryEngine of VectorStoreIndex

packages/core/src/index.ts, packages/core/src/indices/vectorStore/VectorIndexRetriever.ts, packages/core/src/storage/vectorStore/SimpleVectorStore.ts, packages/core/src/storage/vectorStore/types.ts
**Changes**
+ Make VectorStore interface function signatures `async` to support API-based stores, whose operations are all async
+ export VectorStore types so they can be implemented by custom integrations
Ran lint and all tests pass.
=> make VectorStore function signatures unique, export VectorStore types

packages/core/src/storage/vectorStore/types.ts
Since types only exist at compile time, it's very difficult to switch off of an `interface` without a key.
This makes it much easier to `switch` over `MetadataFilter`s and map to other structures, like Pinecone filters.
=> add a filter type to exact match filters

packages/core/src/Node.ts
Without its own constructor, one is created that calls `super` and then sets `indexId` to its default value (`""`). That ends up blanking out any passed-in value :(
=> add constructor to index node so it keeps passed-in indexId

apps/simple/README.md
Hi, just a minimal thing.
The example commands should be inverted otherwise the 1º throws an issue due to no modules yet installed.
=> Update README.md for apps example

packages/core/package.json, packages/core/src/readers/NotionReader.ts, pnpm-lock.yaml
I/F is backward compatible. The core functionality to be crawled was carved out as a separate library, and the logic to crawl the db was added to that library.
- Add Notion DB Suport
- Add method `loadPages`, `toDocuments`
- To allow users to handle the serialization process
- They are also used inside `loadData`
=> Add Notion database support to NotionReader

apps/simple/package.json, apps/simple/vectorIndexFromVectorStore.ts, packages/core/src/QueryEngine.ts, packages/core/src/ResponseSynthesizer.ts, packages/core/src/Retriever.ts, packages/core/src/indices/vectorStore/VectorIndexRetriever.ts, packages/core/src/indices/vectorStore/VectorStoreIndex.ts, packages/eslint-config-custom/index.js, pnpm-lock.yaml
This PR adds severals thing at the same time listed below:
- It adds support for a method available in Python "VectorStoreIndex.fromVectorStore" allowing you to do what's below.
```ts
const vectorStoreIndex = await VectorStoreIndex.fromVectorStore(vectorStore, serviceContext);
```
This allows you to have a vector store index without being forced to insert nodes during it's creation.
- It adds support for pre filters (filters on metadata) - only tested with Pinecone!
- It adds a simple showcase using an already existing pinecone index (free tier) (so we can call `VectorStoreIndex.fromVectorStore` with pre-filters).
- I'm neither fluent in LLM nor pinecone, so I might be doing weird stuff!
Please follow what is described in apps/simple/README.md.
Then, you'll need to add your OpenAI and …
=> VectorStore - Add Method "VectorStoreIndex.fromVectorStore" + Prefilters + Pinecone Demo

packages/core/src/ChatEngine.ts, packages/core/src/ChatHistory.ts, packages/core/src/llm/LLM.ts
- Differentiates between messages sent to the LLM (`requestMessages`) and the whole chat history (`messages`)
- Improved `SummaryChatHistory` to keep chat history after summarizing (that's why we need `requestMessages`). Also added functionality to summarize only every `messagesToSummarize` message.
=> feat: improved chat history summarizer

packages/core/package.json, packages/core/src/ChatEngine.ts, packages/core/src/ChatHistory.ts, packages/core/src/GlobalsHelper.ts, packages/core/src/llm/LLM.ts
- Make usage of `HistoryChatEngine` the same as the usage of `ContextChatEngine`
- Add `LLMMetadata` interface and use it by the `SummaryChatHistory`
- Moved `tokens` function for the calculation of tokens per a set of chat messages to the LLM (as it's LLM specific)
=> Feature: Added `LLMMetadata` interface

examples/readonly.ts, packages/core/src/indices/vectorStore/VectorStoreIndex.ts
Allows to reopen a `VectorStoreIndex` if it's in a read-only file system (see `examples/readonly.ts`).
=> fix: allow readonly indexes

.changeset/good-badgers-train.md, .vscode/settings.json, apps/simple/data/18-1_Changelog.html, apps/simple/html.ts, apps/simple/package.json, packages/core/package.json, packages/core/src/index.ts, packages/core/src/readers/HTMLReader.ts, packages/core/src/readers/SimpleDirectoryReader.ts, pnpm-lock.yaml
Pretty much what the title says.  Adds HTMLReader to core/src/readers, a sample ts file in apps/simple, and a pretty gnarly HTML file in apps/simple/data.
=> Add HTMLReader, sample app and HTML file

packages/core/package.json, packages/core/src/GlobalsHelper.ts, packages/core/src/tests/TextSplitter.test.ts, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/141
Replaces Tiktoken with JS-Tiktoken, a Pure JavaScript port. Both packages are provided by same mantainer.
=> replace tiktoken with js-tiktoken

.gitignore, apps/simple/directory.ts, packages/core/src/readers/SimpleDirectoryReader.ts
Add an observer/callback pattern to the SimpleDirectoryReader.  This callback gives the user information about the start/end of each directory traversal, the import of each file, and any errors encountered.  At each callback, the user can return false to skip the directory, file, or quit importing altogether (in the case of an error report).
I found this functionality very helpful for troubleshooting problems with large document imports, but it will also be useful for managing UX (progress reporting / cancel ability) when the time comes.
=> Add observer/callback feature to SimpleDirectoryReader

packages/create-llama/templates/index.ts
use llamaindex version for referencing llamaindex in the generated `package.json` and not the wrong create-llama version (worked before as both versions have been in sync)
=> fix: use llamaindex version and not create-llama version

packages/create-llama/README.md, packages/create-llama/templates/types/simple/fastapi/app/utils/index.py, packages/create-llama/templates/types/streaming/fastapi/app/utils/index.py
We're pointing people directly to create-llama from our homepage now, so these README docs should be authoriative.
This PR includes a minor change to the Python backend template to explicitly set the LLM, to make it easier for somebody to set it to gpt-4.
=> Expanding README docs

packages/create-llama/templates/types/simple/express/index.ts, packages/create-llama/templates/types/simple/express/src/controllers/chat.controller.ts, packages/create-llama/templates/types/streaming/express/index.ts, packages/create-llama/templates/types/streaming/express/src/controllers/chat.controller.ts
Express middleware was expecting a JSON payload and getting text/plain, so parse the JSON in the controller instead.
There may be a smarter way to do this.
=> fix: generated frontend is sending text/plain

packages/create-llama/templates/types/simple/fastapi/main.py, packages/create-llama/templates/types/streaming/fastapi/main.py
dotenv must load before chat_router or .env isn't picked up in time
=> Fix: env is not loaded in time to prevent erroring out

packages/create-llama/templates/types/simple/fastapi/gitignore, packages/create-llama/templates/types/streaming/fastapi/gitignore
.gitignore should include .env
=> Fix: python backend leaks API key by default

apps/simple/assemblyai.ts, examples/assemblyai.ts, packages/core/src/readers/AssemblyAI.ts
I noticed you have this PR open to re-add AssemblyAI with the latest version.
I took the liberty to update the code to use the new function `transcribe` instead of the deprecated `create`.
=> Feat: Update AssemblyAI reader to use new SDK functions

apps/simple/assemblyai.ts, examples/assemblyai.ts, packages/core/package.json, packages/core/src/index.ts, packages/core/src/readers/AssemblyAI.ts, packages/eslint-config-custom/index.js, pnpm-lock.yaml
AssemblyAI was removed in commit c8bbc101ccc6535c204acb923958341cca753acd as it's not working with NextJS.
The following error happens after creating an example NextJS project with `create-llama` and calling `pnpm dev` and trying to chat:
```
Import trace for requested module:
./app/api/chat/route.ts
⨯ ../../packages/core/dist/index.js:5028:24
Module not found: Default condition should be last one
5026 | 
5027 | // src/readers/AssemblyAI.ts
> 5028 | var import_assemblyai = require("assemblyai");
|                        ^
5029 | var AssemblyAIReader = class {
5030 |   /**
5031 |    * Creates a new AssemblyAI Reader.
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./app/api/chat/route.ts
```
=> Feat: Re-Add AssemblyAIReader 

packages/core/src/llm/LLM.ts
When streaming Azure replies the following as part of a chunk. Notice that there are no `choices`.
```
{
id: '',
object: '',
created: 0,
model: '',
prompt_filter_results: [ { prompt_index: 0, content_filter_results: [Object] } ],
choices: []
}
```
The suggested fix skips over these chunks as so not to cause `TypeError: Cannot set properties of undefined (setting 'index')` error
=> Handle Azure specific responses, where choices could be 0

packages/create-llama/templates/types/streaming/nextjs/app/api/chat/route.ts
Sets max tokens to 512. I talked with @logan-markewich that this is a good default. (2048 is too high for GPT3.5). 
The reason why we have to set a value:
If we don't do so, for the GPT4 Vision model, the stream stops after a couple of characters; see:
=> Fix: Set max tokens to 512 for nextjs examples

examples/astradb/README.md, examples/astradb/load.ts, examples/astradb/query.ts, examples/package.json, packages/core/package.json, packages/core/src/storage/vectorStore/AstraDBVectorStore.ts, packages/eslint-config-custom/index.js, pnpm-lock.yaml
- Updates `@datastax/astra-db-ts` to `0.1.2`
- Connect to AstraDB with `ASTRA_DB_ENDPOINT` instead of DB ID and region
- Align `create` collection functions param `options` to be of type `CreateCollectionOptions`
- Update Readme and examples accordingly
=> Update Astra client and associated type changes

packages/core/src/TextSplitter.ts, packages/core/src/tests/TextSplitter.test.ts
https://github.com/run-llama/llama_index/blob/df9a30d63d402a21ccbbf5948afc68f057d913f2/llama_index/node_parser/text/sentence.py#L20
BREAKING:
remove `unixLineSeparator` and `windowsLineSeparator`, use `EOL` from `node:os` instead
=> fix: align separator with llama_index

.changeset/new-forks-sin.md, packages/create-llama/questions.ts
Since I moved the file structure, the relative file path is also changed.
Upstream: https://github.com/run-llama/LlamaIndexTS/pull/372
I will add a smoke for this case later.
=> fix(create-llama): component choice

.changeset/silly-bugs-fold.md, .github/workflows/e2e.yml, packages/create-llama/create-app.ts, packages/create-llama/e2e/utils.ts, packages/create-llama/helpers/index.ts, packages/create-llama/helpers/poetry.ts, packages/create-llama/helpers/python.ts, packages/create-llama/helpers/types.ts, packages/create-llama/helpers/typescript.ts, packages/create-llama/index.ts, packages/create-llama/questions.ts
- Add checking is poetry installed (using `poetry --version`).
- Add installing python dependencies (using `poetry install`).
- Add generating index in FastAPI app if the environment was set-up correctly (`poetry run python app/engine/generate.py`).
=> Draft: Add poetry installation support for FastAPI

.eslintrc.js, packages/core/src/PromptHelper.ts, packages/core/src/embeddings/utils.ts, packages/core/src/indices/summary/SummaryIndexRetriever.ts, packages/core/src/readers/SimpleMongoReader.ts, packages/core/src/synthesizers/builders.ts
eslint shows errors for functions with more than four parameters
=> refactor: encourage using parameter objects 

.devcontainer/devcontainer.json, .github/workflows/lint_on_push_or_pull.yml, apps/docs/tsconfig.json, examples/tsconfig.json, package.json, packages/core/tsconfig.json, packages/create-llama/e2e/tsconfig.json, packages/create-llama/templates/types/simple/express/tsconfig.json, packages/create-llama/templates/types/streaming/express/tsconfig.json, packages/create-llama/templates/types/streaming/nextjs/tsconfig.json, packages/create-llama/tsconfig.json, pnpm-lock.yaml, tsconfig.json
So it looks like the format run in the GHA is not using the node_modules version of prettier, which was causing the Github Actions to fail: https://github.com/run-llama/LlamaIndexTS/actions/runs/7589497521/job/20675122119?pr=404
Not entirely sure why that was (probably worth taking a look into it if this happens to us repeatedly) but in the meantime, upgrading to the latest version of prettier should hopefully fix the problem.
=> New prettier version

package.json
add package name to top level package.json in order to enable checking out specific commits from npm/yarn/pnpm. Previously if you were referencing a specific commit in your package.json it would fail with the following error. 
` ERR_PNPM_MISSING_PACKAGE_NAME  Can't install git+https://github.com/run-llama/LlamaIndexTS.git#1bd47969b37c86a226f10d1e1a6498de798ca39c: Missing package name`. By adding the name property to the top level package.json this error goes away. 
This enables developers to experiment with features that are not yet published to NPM.
- I created a test app to demonstrate this. clone this repo and checkout this branch: https://github.com/owencraston/test-app/pull/1
- checkout this commit: https://github.com/owencraston/test-app/pull/1/commits/48541659e5d7373b69357868708e899 …
=> fix: Add package name

packages/core/src/Node.ts, packages/core/src/tests/Node.test.ts
@yisding While having fun with https://github.com/run-llama/LlamaIndexTS/pull/306, I found something that looks wrong to me: deserialization of a `Node` generates a new hash. I didn't test this extensively so that I would merge it after the next release. Please have a look.
=> fix: don't create new hash deserialization a node

.changeset/tender-horses-rhyme.md, .prettierignore, examples/together-ai.ts, packages/core/package.json, packages/core/src/embeddings/OpenAIEmbedding.ts, packages/core/src/embeddings/together.ts, packages/core/src/llm/together.ts, pnpm-lock.yaml
Fixed small bugs with the Together.AI integration.
* the init params were being overriden, so for example if the user set an apiKey in the init it would be overriden by the environment variable.
* the example was missing a newline in the output
* if there was no key specified, the user would be prompted for an OpenAI API key
* the OpenAI embeddings interface didn't allow model specification (which didn't matter when there was only one supported model)
=> minor bug fixes with together AI

packages/create-llama/templates/types/simple/express/package.json, packages/create-llama/templates/types/streaming/express/package.json, packages/create-llama/templates/types/streaming/nextjs/package.json
ChromaDB version `1.8.1` cannot resolve `chromadb-default-embed` when compiling create-llama project.
Log:
```
•/node_modules/chromadb/dist/chromadb.mjs:2431:33
Module not found: Can't resolve 'chromadb-default-embed'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
/node_modules/llamaindex/dist/index.mjs
• /app/api/chat/route.ts
```
This PR reverts commit ae13525bd618495ba2ce8661ffc55b624d9a7240.
The issue only occurs in NextJS when user access the UI then send a chat message.
The `Frontend should be able to submit a message and receive a response` already cover this issue.
**Run a NextJS test case:**
```shell
npx playwright test -g "nextjs.*shadcn.*Frontend should be able to submit a message and receive a response"
```
-> Failure log:
```
Connected!
✓ …
```
=> ChromaDB can't resolve 'chromadb-default-embed'

.changeset/shy-cars-know.md, packages/create-llama/templates/types/simple/express/gitignore, packages/create-llama/templates/types/streaming/express/gitignore
As the title says
Locally ran the CLI 2x:
* Express + Chat without streaming 
* Express + Chat with streaming
Saw that the output had the updated .gitignore file.
=> Add node_modules to gitignore in Express backends

packages/core/src/extractors/index.ts
This change exposes the BaseExtractor class, allowing you to define your own metadata extractors.
=> Expose BaseExtractor Class

README.md, examples/chromadb/README.md
Hello!
This pull request updates two of the README files to use `pnpm dlx` instead of `pnpx`.
Due to the [deprecation/removal of `pnpx`](https://github.com/pnpm/pnpm/pull/3652), the current examples in the READMEs may not work for some users. There are also no docs for the `pnpx` command on pnpm.io now that it's removed. As of its deprecation in pnpm 6.x, it is now recommended to use [`pnpm dlx`](https://pnpm.io/cli/dlx) instead.
=> fix: update deprecated pnpx to pnpm dlx

apps/docs/docs/getting_started/concepts.md, apps/docs/docs/getting_started/installation.mdx, apps/docs/docs/introduction.md, apps/docs/docs/modules/agent/index.md, apps/docs/docs/modules/query_engines/index.md
Hello!
I discovered that several of the links in the docs are broken and simply redirect to a 404 page. This pull request fixes most of the broken links that I found. I also updated one of the file references, `.zshrc/.bashrc`, to be formatted as inline code.
It also appears that the "End-to-End Tutorials" link is broken in `apps/docs/introduction.md` (the docs home page). However, I couldn't find the correct URL for this. Any ideas as to what the correct URL is?
=> docs: fix broken relative links in docs

packages/core/src/readers/NotionReader.ts
When using the NotionReader `Document` objects do not have the same ID as the Notion document they represent. This looks to simply be an oversight, rather than intended behavior. The Notion document ID is available.
Use the Notion document ID as the ID of the `Document` object. This ensures consistent `id_`s for each ingestion run.
=> Consistent Document IDs in NotionReader.ts

packages/core/src/indices/summary/index.ts, packages/core/src/indices/vectorStore/index.ts, packages/core/tests/indices/SummaryIndex.test.ts
fixes: https://github.com/run-llama/LlamaIndexTS/discussions/547#discussioncomment-8465573
=> fix: SummaryIndex and VectorStoreIndex must be able to share storage context

.changeset/afraid-toys-fetch.md, examples/longText.ts, packages/core/src/nodeParsers/SimpleNodeParser.ts
=> fix: enable split long sentence by default

packages/core/src/llm/ollama.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/587
params like `maxTokens` is depends on model itself so we don't know
=> fix: allow passing model metadata

.changeset/eight-dogs-burn.md, packages/core/src/indices/index.ts, packages/core/src/indices/json-to-index-struct.ts, packages/core/tests/indices/json-to-index-struct.test.ts
Fixes #609 
Add missing exports to 
```
IndexStructType,
IndexDict,
jsonToIndexStruct,
IndexList,
IndexStruct
```
Also added unit tests to `jsonToIndexStruct`. They caught an issue in `IndexDict.toJson()` method so fixed that as well.
=> fix: Restore missing exports, fix IndexDict.toJson()

examples/qdrantdb/README.md, examples/qdrantdb/preFilters.ts, packages/core/src/storage/vectorStore/QdrantVectorStore.ts
While using Qdrant as a vectorstore in a query engine the filters didn't work. This is a fix for the same.
=> Fix: Metadata filters doesn't seem to work for Qdrant

.changeset/nine-fireants-bow.md, packages/core/src/llm/azure.ts
This is an update to the list of Azure OpenAI versions.  While this constant appears to be purely informational, it would be good if it were kept up to date or removed.
This PR updates the list, adding several missing entries and removing entries being retired as of April 2, 2024 (next Tuesday)
=> Update to latest supported version list as of 2024-04-02. 

.changeset/young-bananas-wave.md, packages/core/src/indices/vectorStore/index.ts, packages/core/src/ingestion/IngestionPipeline.ts, packages/core/src/ingestion/strategies/UpsertsAndDeleteStrategy.ts, packages/core/src/ingestion/strategies/index.ts, packages/core/tests/indices/VectorStoreIndex.test.ts
- Adding the same doc store strategies from IngestionPipeline to VectorStoreIndex.fromDocuments
- Prevents duplicate issues like https://github.com/run-llama/LlamaIndexTS/issues/639
=> feat: Add doc store strategies to VectorStoreIndex.fromDocuments

examples/package.json, examples/recipes/cost-analysis.ts, packages/core/src/ChatHistory.ts, packages/core/src/GlobalsHelper.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/base.ts, packages/core/src/llm/mistral.ts, packages/core/src/llm/ollama.ts, packages/core/src/llm/types.ts, pnpm-lock.yaml
Closes: https://github.com/run-llama/LlamaIndexTS/pull/667, https://github.com/run-llama/LlamaIndexTS/issues/664
I'm removing this API since most of the LLM classes don't have an accurate function (only OpenAI supports it), and there are runtime errors.
But I put code into `examples/recipes/cost-analysis.ts` to let users know how to implement it by theirselves.
=> refactor: remove `llm.tokens` api

examples/chatHistory.ts, packages/core/src/GlobalsHelper.ts, packages/core/src/Retriever.ts, packages/core/src/agent/openai/worker.ts, packages/core/src/callbacks/CallbackManager.ts, packages/core/src/cloud/LlamaCloudRetriever.ts, packages/core/src/engines/chat/CondenseQuestionChatEngine.ts, packages/core/src/engines/chat/ContextChatEngine.ts, packages/core/src/engines/chat/DefaultContextGenerator.ts, packages/core/src/engines/chat/SimpleChatEngine.ts, packages/core/src/engines/chat/types.ts, packages/core/src/engines/query/RetrieverQueryEngine.ts, packages/core/src/engines/query/SubQuestionQueryEngine.ts, packages/core/src/indices/summary/index.ts, packages/core/src/indices/vectorStore/index.ts, packages/core/src/internal/context/EventCaller.ts, packages/core/src/internal/utils.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/base.ts, packages/core/src/llm/mistral.ts, packages/core/src/llm/ollama.ts, packages/core/src/llm/types.ts, packages/core/src/llm/utils.ts, packages/core/src/synthesizers/MultiModalResponseSynthesizer.ts, packages/core/src/synthesizers/ResponseSynthesizer.ts, packages/core/src/synthesizers/builders.ts, packages/core/src/synthesizers/types.ts, packages/core/src/types.ts, packages/core/tests/CallbackManager.test.ts, packages/core/tests/utility/mockOpenAI.ts
Use `AsyncLocalStoarge` to pass context through async function. You can track who trigger this event by using this
```ts
if (process.env.NODE_ENV === "development") {
Settings.callbackManager.on("llm-end", (event) => {
console.log("callers chain", event.reason?.computedCallers);
});
}
```
```shell
callers chain [
OpenAI {
model: 'gpt-3.5-turbo',
temperature: 0.1,
topP: 1,
maxTokens: 3072,
additionalChatOptions: undefined,
apiKey: undefined,
maxRetries: 10,
timeout: 60000,
session: OpenAISession { openai: [OpenAI] },
additionalSessionOptions: undefined,
chat: [Function (anonymous)],
streamChat: [Function (anonymous)]
},
SimpleChatEngine {
chatHistory: SimpleChatHistory { messages: [], messagesBefore: 0 },
llm: OpenAI {
model: 'gpt-3.5-turbo',
temperature: 0.1,
topP: 1,
maxTokens: 3072, …
```
=> refactor: use `event.reason`, remove `parentEvent`

examples/agent/wiki.ts, packages/core/src/agent/openai/base.ts, packages/core/src/agent/openai/worker.ts, packages/core/src/agent/react/worker.ts, packages/core/src/agent/runner/base.ts, packages/core/src/memory/ChatMemoryBuffer.ts
I found this issue while testing the `WikipediaTool,` which quickly fills up the agent's memory (see `examples/agent/wiki.ts`).
The default token limit of `ChatMemoryBuffer` is too small for LLMs with larger context windows. 
So it's a good idea to use one that's specific to the selected LLM.
=> fix: use LLM's context window to specify agent's token limit

examples/jsonExtract.ts, examples/recipes/cost-analysis.ts, packages/core/src/ChatHistory.ts, packages/core/src/agent/openai/worker.ts, packages/core/src/agent/react/types.ts, packages/core/src/agent/react/worker.ts, packages/core/src/engines/chat/ContextChatEngine.ts, packages/core/src/engines/chat/SimpleChatEngine.ts, packages/core/src/evaluation/Correctness.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/anthropic.ts, packages/core/src/llm/base.ts, packages/core/src/llm/open_ai.ts, packages/core/src/llm/types.ts, packages/core/src/llm/utils.ts, packages/core/src/selectors/llmSelectors.ts, tsconfig.json
Related: https://github.com/run-llama/LlamaIndexTS/issues/692
=> fix: message content type

apps/docs/docs/recipes/cost-analysis.mdx, examples/package.json, examples/recipes/cost-analysis.ts, packages/core/e2e/fixtures/llm/open_ai.ts, packages/core/e2e/node/snapshot/agent.snap, packages/core/e2e/node/snapshot/gpt-4-turbo.snap, packages/core/e2e/node/snapshot/llm.snap, packages/core/e2e/node/snapshot/queryEngine_subquestion.snap, packages/core/e2e/node/utils.ts, packages/core/src/callbacks/CallbackManager.ts, packages/core/src/llm/LLM.ts, packages/core/src/llm/anthropic.ts, packages/core/src/llm/mistral.ts, packages/core/src/llm/ollama.ts, packages/core/src/llm/open_ai.ts, packages/core/src/llm/types.ts, packages/core/src/llm/utils.ts, pnpm-lock.yaml
Related: https://github.com/run-llama/LlamaIndexTS/issues/664
=> feat: add `llm-stream` event

README.md, examples/multimodal/load.ts, packages/core/e2e/fixtures/embeddings/OpenAIEmbedding.ts, packages/core/src/embeddings/MultiModalEmbedding.ts, packages/core/src/embeddings/types.ts, packages/core/src/indices/vectorStore/index.ts
Refactor VectorStoreIndex: use `TransformerComponent` to calc embeddings (for image nodes and non-image nodes)
=> refactor: VectorStoreIndex: use TransformerComponent to calc embeddings 

packages/core/src/ingestion/IngestionPipeline.ts
if `reader.loadData` return large amount of documents, the `IngestionPipeline.prepareInput` will throw "RangeError: Maximum call stack size exceeded", use Array.concat to avoid it.
=> fix: use Array.prototype.flat instead of Array.prototype.push(...spread)

packages/core/tests/ingestion/ingestion-pipeline.test.ts
Upstream: https://github.com/run-llama/LlamaIndexTS/pull/760
=> test: load large amount of data won't cause error

.changeset/light-ears-begin.md, apps/docs/docs/modules/embeddings/available_embeddings/gemini.md, apps/docs/docs/modules/llms/available_llms/gemini.md, examples/gemini.ts, examples/gemini/chat.ts, packages/core/package.json, packages/core/src/embeddings/GeminiEmbedding.ts, packages/core/src/embeddings/index.ts, packages/core/src/index.ts, packages/core/src/llm/gemini.ts, packages/core/src/llm/index.ts, packages/edge/package.json, pnpm-lock.yaml
Follow logic from llama-index repo:
https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
=> feat: init gemini llm

packages/core/e2e/fixtures/llm/anthropic.ts, packages/core/src/llm/index.ts
@marcusschiesser @himself65 why did we move away from just export * from every file in the directory? Is there a benefit to doing so? Clear downside is that we'll often forget to re-export things.
=> fix(core): add more exports on `llm/index`

.changeset/rude-ducks-invent.md, examples/.env.example, examples/agent/openai.ts, packages/core/src/Settings.ts, packages/core/src/agent/anthropic.ts, packages/core/src/agent/base.ts, packages/core/src/agent/openai.ts, packages/core/src/agent/react.ts, packages/core/src/agent/types.ts, packages/core/src/agent/utils.ts, packages/core/src/engines/chat/types.ts, packages/core/src/internal/logger.ts
Adding `verbose` back, I removed this a month ago because I thought most of the logging was a mess.
For now, in Agent part, you can `DEBUG=llamaindex node ./code.js` or set verbose=true
=> feat: add verbose mode to Agent

.changeset/six-needles-poke.md, packages/core/src/callbacks/CallbackManager.ts
Here is a pitfall inside tool-call-result, it can return anything, so we cannot just clone the detail.
But here is another issue that you can modify value inside the callback manager, but I think no one will do it
=> fix: remove clone object in `CallbackManager.dispatchEvent`

.changeset/silly-horses-carry.md, packages/core/src/storage/vectorStore/PGVectorStore.ts
The SQL is comparing the parameter vector with the embeddings column using "<=>" operator. "<->" is used for vector distance calculations. The change now matches with the code in the Python package.
=> fix: change <-> to <=> in the SELECT query

.changeset/brown-suits-thank.md, .changeset/itchy-paws-love.md, examples/ollama.ts, packages/core/src/embeddings/index.ts, packages/core/src/index.ts, packages/core/src/llm/index.ts, packages/core/src/llm/ollama.ts
Allow user to change `host` of ollama
I realized that ollama might could be used in all js runtime even you are deploying it (maybe), so I export it for all js runtime by default
=> feat: allow to change ollama port

packages/core/src/storage/vectorStore/PGVectorStore.ts
Similarity score should be 1 minus the resulting value from the PG cosine distance. This change now matches with the Python package.
=> fix: PGVector similarity score

packages/core/src/readers/LlamaParseReader.ts
As requested, 1st part of #808 only adding File Type Support to be up to date with python version
=> feat: LlamaParseReader: update Supported File Types to match python version

.changeset/wet-boxes-compete.md, examples/package.json, packages/core/package.json, pnpm-lock.yaml
Because chromadb haven't released a newer version from 1.8.1 yet so we still have the issue mentioned in: https://github.com/run-llama/LlamaIndexTS/pull/417
This PR downgrades the chromadb package to 1.7.3 again
=> chore: rollback chromadb version to 1.7.3

.changeset/sharp-knives-ring.md, packages/core/src/Prompt.ts, packages/core/src/llm/gemini.ts, packages/core/src/llm/index.ts
Gemini was completely broken for text chat and was getting confused when prompted with an empty context.
It is still broken for vision. Currently the `mimeType` is incorrect and `inlineData` isn't taken into account. Will submit a separate PR to address.
=> fix: Gemini text chat - prevent sending broken messageContent and history

.github/workflows/test.yml, package.json, packages/core/.madgerc, packages/core/package.json, packages/core/src/Node.ts, packages/core/src/Settings.ts, packages/core/src/indices/vectorStore/index.ts, packages/core/src/internal/decorator/node.ts, packages/core/src/internal/settings/chunk-size.ts, packages/core/src/storage/docStore/KVDocumentStore.ts, packages/core/src/storage/docStore/utils.ts, packages/core/tests/Embedding.test.ts, packages/core/tests/Node.test.ts, packages/core/tests/indices/VectorStoreIndex.test.ts, packages/core/tests/tsconfig.json, packages/env/.madgerc, packages/env/jsr.json, packages/env/package.json, pnpm-lock.yaml, turbo.json
Not a breaking change. Related https://github.com/run-llama/LlamaIndexTS/issues/739
Update:
1. remove `Object.assign(this, init)` which is not a type-safe way.
2. put madge circular check on top level
3. adding more strong type check place
=> feat: improve BaseNode

.changeset/calm-owls-notice.md, packages/core/src/agent/base.ts, packages/core/src/agent/openai.ts, packages/env/package.json, packages/env/src/index.ts, packages/env/src/polyfill.ts, pnpm-lock.yaml
I'm writing a Cloudflare worker and found that `readable-stream` cannot be parsed correctly because it uses the CJS format. So I will remove `pipeline` API since we can do the same thing in other way
=> fix: remove non-standard API `pipeline`

.changeset/good-carpets-rhyme.md, packages/core/src/readers/MarkdownReader.ts
The current MarkdownReader doesn't support text before headings. This PR fixes this issue
=> fix: text before heading in markdown reader

.changeset/twelve-bottles-wait.md, apps/docs/i18n/fr/docusaurus-plugin-content-docs/current/api/classes/BaseDocumentStore.md, apps/docs/i18n/hr/docusaurus-plugin-content-docs/current/api/classes/BaseDocumentStore.md, apps/docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/api/classes/BaseDocumentStore.md, packages/core/src/indices/BaseIndex.ts, packages/core/src/indices/keyword/index.ts, packages/core/src/indices/summary/index.ts, packages/core/src/ingestion/strategies/DuplicatesStrategy.ts, packages/core/src/storage/docStore/types.ts
Even if used as an async function in multiple places the current implementation of setDocumentHash isn't declared that way.
This PR fixes this issue
=> fix: setDocumentHash should be async

.changeset/neat-flowers-ring.md, apps/docs/docs/modules/llms/available_llms/bedrock.md, packages/community/.cjs.swcrc, packages/community/.swcrc, packages/community/jsr.json, packages/community/package.json, packages/community/src/index.ts, packages/community/src/llm/bedrock/base.ts, packages/community/src/llm/bedrock/types.ts, packages/community/src/llm/bedrock/utils.ts, packages/community/tsconfig.json, packages/core/src/llm/index.ts, pnpm-lock.yaml
Only Anthropic is supported but others can be added by adding a `Provider` class
Usage (using api keys - there are other methods):
```ts
const bedrock = new Bedrock({
model: BEDROCK_MODELS.ANTHROPIC_CLAUDE_3_HAIKU,
region: "us-east-1",
credentials: {
accessKeyId: "...",
secretAccessKey: "...",
},
});
```
=> feat: Bedrock support added, only for Anthropic models

packages/core/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
Also, the delete function was wrong. Each document will have multiple nodes, so "deleteOne" will not remove all of the nodes for a single document.
=> cannot pass embedModel to MongoDBAtlasVectorStore

.changeset/angry-eagles-dress.md, packages/core/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
When requesting the MongoDB Atlas store, the result could be inaccurate - especially when only requesting a small amount of items. To tune the result, this PR adds the option to set the `numCandiates` vectorSearch option
=> feat: add numCandidates setting to MongoDBAtlasVectorStore for tuning queries

.changeset/nasty-peas-exercise.md, examples/agent/large_toolcall.ts, packages/core/src/agent/utils.ts
Problem: A partial JSON is returned by the LLM of the agent if the `maxTokens` parameter is too small (Tested with OpenAI's GPT4-Turbo). 
Changes:
- Show an error message if an agent tool is called with a partial JSON. Hint the user to increase `maxTokens`
- Don't stop agent execution
=> fix: calling tools with large inputs

.changeset/proud-geckos-greet.md, packages/core/src/readers/LlamaParseReader.ts
Testing looks good, pure json results are as expected. 
I'm a bit unsure about how to further use the json results tho.
Is there a function akin to this python [example](https://github.com/run-llama/llama_parse/blob/main/examples/demo_json.ipynb): 
Especially, is there an existing way to use this part:
```
json_objs = parser.get_json_result("./uber_10q_march_2022.pdf")
json_list = json_objs[0]["pages"]
```
In LlamaIndexTS? 
My idea would be to use` jsonToNode` afterwards to turn the results into proper Nodes for further processing. Or am I missing something?
Also restructured most of LlamaParseReader to align more closely with the python version. This modular approach should avoid redundant code.
=> feat: add json mode and image retrieval to LlamaParse

apps/docs/docs/introduction.md
Replaced the Broken link on **Starter Tutorial** on https://ts.llamaindex.ai/#getting-started
Broken Link: https://ts.llamaindex.ai/getting_started/starter.mdx
Changed to: https://ts.llamaindex.ai/getting_started/starter_tutorial/retrieval_augmented_generation
fixes https://github.com/run-llama/LlamaIndexTS/issues/931
=> docs: fixed the broken link on Getting Started Section

.changeset/odd-insects-vanish.md, packages/env/src/index.workerd.ts, packages/env/src/tokenizers/node.ts
- Use tiktoken instead of tiktoken/lite (for WASM)
- Disable WASM tiktoken for non-Node environments
=> fix: Use tiktoken instead of tiktoken/lite 

apps/docs/docs/modules/data_loaders/llama_parse/json_mode.mdx
just a small update to show how to use `LlamaParse` JSON mode with `SimpleDirectoryReader`
=> docs: LlamaParse JSON + SimpleDirectoryReader

.changeset/new-worms-teach.md, examples/readers/src/custom-simple-directory-reader.ts, packages/llamaindex/src/readers/CSVReader.ts, packages/llamaindex/src/readers/DocxReader.ts, packages/llamaindex/src/readers/HTMLReader.ts, packages/llamaindex/src/readers/ImageReader.ts, packages/llamaindex/src/readers/LlamaParseReader.ts, packages/llamaindex/src/readers/MarkdownReader.ts, packages/llamaindex/src/readers/PDFReader.ts, packages/llamaindex/src/readers/TextFileReader.ts, packages/llamaindex/src/readers/type.ts, packages/llamaindex/tests/indices/json-to-index-struct.test.ts, packages/llamaindex/tests/readers/pdf-reader.test.ts
- use Uint8Array for readers `loadDataAsContent` method
- Add common metadata to PDFs
=> fix: Add metadata to PDFs and use Uint8Array for readers content

README.md
Remove the CloudFlare support declaration because it is not designed for importing a framework-level code.
In the future, we could only officially support for import `@llamaindex/core` package and some llm/embedding API,
=> docs: remove cloudflare worker section

.changeset/fluffy-knives-glow.md, packages/llamaindex/src/llm/gemini/base.ts, packages/llamaindex/src/llm/gemini/utils.ts, packages/llamaindex/src/llm/gemini/vertex.ts
This pull request disables external filters for Google Gemini models. This could fix errors like this:
```
Error: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY
```
The modification is based on the [official documentation](https://ai.google.dev/gemini-api/docs/safety-settings).
=> fix: disable External Filters for Gemini

.changeset/witty-bats-shave.md, apps/docs/docs/modules/data_loaders/llama_parse/index.mdx, packages/cloud/openapi.json, packages/llamaindex/CHANGELOG.md, packages/llamaindex/src/readers/LlamaParseReader.ts
A typo in the parameter made it impossible to change the default page separator on LlamaParse (`\n---\n`). This PR fixes the issue.
Related issues:
- #924 
- https://github.com/run-llama/llama_parse/issues/263
- https://github.com/run-llama/llama_parse/issues/223
- https://github.com/run-llama/llama_parse/issues/230
I also fixed a few typo from the same doc page.
=> fix: typo in custom page separator parameter for LlamaParse

.changeset/short-plants-sip.md, packages/core/src/global/settings/callback-manager.ts, packages/core/tests/event-system.test.ts
In #1026, `CallbackManager.dispatchEvent` was changed from [using a spread operator](https://github.com/run-llama/LlamaIndexTS/blob/llamaindex%400.4.14/packages/llamaindex/src/callbacks/CallbackManager.ts#L223-L225) to using `structuredClone`. This breaks with `llm-tool-result` events, since `FunctionTool` has an `_fn` property with the original function. `structuredClone` throws a `DataCloneError` since it cannot clone functions.
I'm not sure if there was more motivation behind using `structruedClone`, but I've added a test to reproduce the error with a simplified event, and changed `dispatchEvent` back to using a spread operator to perform a shallow clone of the event detail.
=> fix: DataCloneError when using FunctionTool

.changeset/famous-poets-hammer.md, examples/metadata-filter/milvus.ts, examples/metadata-filter/simple.ts, examples/milvus/query.ts, packages/llamaindex/src/storage/vectorStore/MilvusVectorStore.ts, packages/llamaindex/src/storage/vectorStore/PGVectorStore.ts, packages/llamaindex/src/storage/vectorStore/PineconeVectorStore.ts, packages/llamaindex/src/storage/vectorStore/SimpleVectorStore.ts, packages/llamaindex/src/storage/vectorStore/types.ts, packages/llamaindex/src/storage/vectorStore/utils.ts, packages/llamaindex/tests/mocks/TestableMilvusVectorStore.ts, packages/llamaindex/tests/vectorStores/MilvusVectorStore.test.ts, packages/llamaindex/tests/vectorStores/SimpleVectorStore.test.ts
- Mark ExactMatchFilter as deprecated and use MetadataFilter with many supported operations
- Support `OR` and `AND` condition
- Support new operators: EQ, IN
- Add filtering for MilvusVectorStore first
- Support more operators
- Add tests and examples with all operators for SimpleVectorStore and Milvus
Sample filter:
```
const queryEngineOR = index.asQueryEngine({
preFilters: {
filters: [
{
key: "private",
value: "false",
operator: "==",
},
{
key: "dogId",
value: ["1", "3"],
operator: "in",
},
],
condition: "or",
}
});
```
=> feat: Support MetadataFilters for Milvus and SimpleVectorStore

apps/docs/docs/modules/retriever.md
`retriever.similarityTopK = 3;` is deprecated, changed for `retriever.topK = { TEXT: 3, IMAGE: 1 };` [here](https://ts.llamaindex.ai/modules/retriever)
=> docs: fix deprecated similarityTopK for retriever

.changeset/tender-mice-retire.md, packages/llamaindex/src/llm/replicate_ai.ts
In the `ReplicateLLM` class, the `maxTokens` option was not being passed to the replicate's api when calling the `chat()` method.
=> fix: passing max_token option to replicate's api call

.changeset/chilled-tomatoes-visit.md, apps/docs/docs/modules/data_loaders/llama_parse/index.mdx, packages/llamaindex/src/readers/LlamaParseReader.ts
Translates and uses this new python method:
```
def _get_sub_docs(docs: List[Document]) -> List[Document]:
"""Split docs into pages, by separator."""
sub_docs = []
for doc in docs:
doc_chunks = doc.text.split("\n---\n")
for doc_chunk in doc_chunks:
sub_doc = Document(
text=doc_chunk,
metadata=deepcopy(doc.metadata),
)
sub_docs.append(sub_doc)
return sub_docs
```
Not really sure about the relationship of `pageSeperator` (gets sent to the API) and the new split by page mode atm
=> feat: add split by page mode to LlamaParseReader

.changeset/real-seahorses-divide.md, packages/core/src/node-parser/base.ts
See https://github.com/run-llama/LlamaIndexTS/issues/1098
=> fix: metadata should not be included after sentence splitter

.changeset/tough-cups-doubt.md, packages/llamaindex/src/engines/chat/ContextChatEngine.ts, packages/llamaindex/src/engines/chat/DefaultContextGenerator.ts
Should use mode LLM to generating context in ContextChatEngine LITS.
See Python usage: https://github.com/run-llama/llama_index/blob/96a196a9d0bed9ea8a3b9f9caac18639faaf0249/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L167-L169
=> fix: use metadata mode LLM for generating context

apps/docs/docs/modules/ingestion_pipeline/index.md, apps/docs/docs/modules/ingestion_pipeline/transformations.md, apps/docs/docs/modules/node_parser.md, apps/docs/docs/modules/query_engines/router_query_engine.md, examples/agent/multi_document_agent.ts, examples/extractors/keywordExtractor.ts, examples/extractors/questionsAnsweredExtractor.ts, examples/extractors/summaryExtractor.ts, examples/extractors/titleExtractor.ts, examples/jupyter/nodeparser.ipynb, examples/lowlevel.ts, examples/pipeline/ingestion.ts, examples/routerQueryEngine.ts, examples/summaryIndex.ts, packages/llamaindex/tests/MetadataExtractors.test.ts, packages/llamaindex/tests/ingestion/IngestionCache.test.ts
`SimpleNodeParser` as a name is deprecated and its implementation just points to `SentenceSplitter`.
This replaces references to `SimpleNodeParser` in the docs with `SentenceSplitter` as well as updating any example code using `SimpleNodeParser` to `SentenceSplitter`. Finally there were two tests using `SimpleNodeParser` and they have also been updated to use `SentenceSplitter`.
=> Updates references to SimpleNodeParser to SentenceSplitter.

examples/agent/openai-task.ts, examples/agent/react-task.ts, examples/tsconfig.json, packages/env/src/index.ts, packages/env/src/polyfill.ts, packages/llamaindex/e2e/examples/cloudflare-worker-agent/src/index.ts, packages/llamaindex/e2e/tsconfig.json, packages/llamaindex/src/agent/base.ts, packages/llamaindex/src/agent/react.ts, packages/llamaindex/src/agent/types.ts, packages/llamaindex/src/agent/utils.ts, packages/llamaindex/src/internal/utils.ts
remove polyfill because originally we use this for type check but now TypeScript >5.4 already add this type `DOM.AsyncIterator` so I think it's safe to remove the polyfill now.
=> fix: remove Stream API polyfill

.changeset/red-vans-taste.md, examples/mongodb/2_load_and_index.ts, examples/mongodb/3_query.ts, packages/llamaindex/src/storage/vectorStore/MongoDBAtlasVectorStore.ts
- Able to populate metadata fields that need for filtering (Done)
- Build mongodb filters based on operator (TODO)
=> feat: implement filters for MongoDBAtlasVectorSearch

.changeset/new-tools-help.md, .changeset/six-frogs-thank.md, packages/llamaindex/src/storage/vectorStore/PGVectorStore.ts
Closes: #1153 
It will now:
- throw an error if there is an insertion error.
- Upsert documents with the same id.
- add all documents to the database as a single `INSERT` call (inside a transaction).
=> fix: database insertion for PGVectorStore

.changeset/yellow-donkeys-complain.md, packages/llamaindex/src/embeddings/JinaAIEmbedding.ts
Modifications:
- renamed parameter: `task_type` to `task`
- extended parameter: `late_chunking`
=> chore: add 'late_chunking' for Jina embedding

.changeset/fluffy-apes-guess.md, packages/llamaindex/src/storage/docStore/PostgresDocumentStore.ts, packages/llamaindex/src/storage/indexStore/PostgresIndexStore.ts, packages/llamaindex/src/storage/kvStore/PostgresKVStore.ts
Allow initializing with pg client or pool instance (just like the PGVectorStore).
=> fix: update `PostgresKVStore` constructor params

.changeset/gorgeous-bees-hide.md, packages/llamaindex/src/ingestion/IngestionCache.ts, packages/llamaindex/src/storage/docStore/KVDocumentStore.ts, packages/llamaindex/src/storage/docStore/PostgresDocumentStore.ts, packages/llamaindex/src/storage/docStore/types.ts, packages/llamaindex/src/storage/docStore/utils.ts
- allow querying documents `__data__` in `pg` by storing plain JSON
- avoid performance costs involved with `parse`/`stringify`
=> fix: add `serializer` in doc store

.changeset/nine-carpets-jam.md, packages/llm/openai/src/llm.ts
llama openai is not streaming token usage even when
```
additionalChatOptions: {
stream: true,
stream_options: {
include_usage: true
}
}
```
is passed into LlamaOpenAI,
The fix will allow user to get token usage provided by OpenAI when streaming.
=> fix: openai streaming with token usage and finish_reason

.changeset/violet-buckets-joke.md, packages/llamaindex/src/index.edge.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1271
=> fix: export llama reader in non-nodejs runtime

.changeset/forty-swans-tan.md, packages/core/src/schema/node.ts, packages/llamaindex/tests/indices/VectorStoreIndex.test.ts
Fixes: #1278
This PR addresses issue #1278 where the id_ field was not being correctly passed as the id when creating a TextNode. This caused the upsert operation to the vector database to rely on the idGenerator instead of using the provided document ID, if available.
Changes:
Updated the logic for creating TextNode to ensure the id_ is set as the document ID when available.
This ensures that when upserting to the vector database, the correct document ID is used, avoiding the generation of unnecessary random IDs.
This fix improves consistency in ID handling, ensuring that document IDs are properly retained in the vector database.
=> fix: ensure `id_` is correctly passed during creation

.changeset/tame-squids-clean.md, examples/metadata-filter/preFilters.ts, examples/vectorIndexCustomize.ts, examples/vectorIndexFromVectorStore.ts, packages/llamaindex/src/cloud/LlamaCloudIndex.ts, packages/llamaindex/src/engines/query/RetrieverQueryEngine.ts, packages/llamaindex/src/indices/keyword/index.ts, packages/llamaindex/src/indices/summary/index.ts, packages/llamaindex/src/indices/vectorStore/index.ts
- remove `preFilters` inside `RetrieverQueryEngine` because it is outdated and I cannot find any places use it.
- `asQueryEngine` doesn't pass `preFilters` to retriever creation function. It made all examples about using filters inside vectorstore ran fail because VectorStore doesn't receive query.filters when using `asQueryEngine`
=> fix: preFilters doesnot work with asQueryEngine

.changeset/yellow-birds-protect.md, examples/qdrantdb/preFilters.ts, packages/llamaindex/src/vector-store/QdrantVectorStore.ts
Implement metadata filters for vector stores (based on Python code)
- Qdrant filters: https://github.com/run-llama/llama_index/blob/2068d14732894962bc1c21dbf5cfe07e7f39f2f7/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py#L1122
=> feat: add metadata filters for vector stores

.changeset/rare-sheep-search.md, packages/llamaindex/src/next.ts
Webpack is unable to resolve a dynamic import in unpdf package:
https://github.com/unjs/unpdf/blob/ca834860d9720830c4bfa4927f076cc2af432dfa/src/utils.ts#L71
And it cause this warning when using with NextJs:
```
⚠ ../../LlamaIndexTS/node_modules/.pnpm/unpdf@0.11.0_encoding@0.1.13/node_modules/unpdf/dist/pdfjs.mjs
Critical dependency: the request of a dependency is an expression
Import trace for requested module:
../../LlamaIndexTS/node_modules/.pnpm/unpdf@0.11.0_encoding@0.1.13/node_modules/unpdf/dist/pdfjs.mjs
../../LlamaIndexTS/node_modules/.pnpm/unpdf@0.11.0_encoding@0.1.13/node_modules/unpdf/dist/index.mjs
../../LlamaIndexTS/packages/llamaindex/dist/readers/PDFReader.js
../../LlamaIndexTS/packages/llamaindex/dist/readers/SimpleDirectoryReader.js
./app/api/chat/engine/loader.ts …
```
=> fix: ignore webpack resolve unpdf for nextjs

.changeset/gold-cameras-wave.md, packages/cloud/src/reader.ts
Parse Job failures fail with almost no useful information.  This includes the error code for visibiltiy.
=> feat: log api response from failed parse jobs

.changeset/twenty-camels-burn.md, packages/llamaindex/src/next.ts
fixes https://github.com/run-llama/create-llama/issues/384
=> fix: unable to resolve unpdf in nextjs

.changeset/funny-drinks-argue.md, packages/llamaindex/src/next.ts
I got this warning related to `replicate` package when using it in NextJs create-llama template
```
⚠ ../../../LlamaIndexTS/node_modules/.pnpm/replicate@1.0.1/node_modules/replicate/lib/util.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Import trace for requested module:
../../../LlamaIndexTS/node_modules/.pnpm/replicate@1.0.1/node_modules/replicate/lib/util.js
../../../LlamaIndexTS/node_modules/.pnpm/replicate@1.0.1/node_modules/replicate/index.js
../../../LlamaIndexTS/packages/providers/replicate/dist/index.js
../../../LlamaIndexTS/packages/llamaindex/dist/llm/replicate_ai.js
../../../LlamaIndexTS/packages/llamaindex/dist/llm/index.js
../../../LlamaIndexTS/packages/llamaindex/dist/index.edge.js …
```
=> fix: replicate deps warning in nextjs

.changeset/late-apricots-yell.md, .changeset/thick-ways-visit.md, examples/cloud/query.ts, packages/core/src/indices/prompt-helper.ts
- remove chunk size limit for prompt helper (as in Python framework). This allows utilizing the whole context window of an LLM for response synthesizers and therefore `files_via_content` retrieval is not resulting in a 'hanging' process anymore
- add example for files_via_content_retrieval
=> Allow files_via_content retrieval from LlamaCloud

.changeset/pretty-swans-fly.md, packages/core/src/response-synthesizers/base-synthesizer.ts, packages/core/src/response-synthesizers/factory.ts, packages/core/src/schema/type/engine–response.ts
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1389
=> fix: source nodes is empty

.changeset/tough-oranges-itch.md, apps/docs/docs/examples/context_aware_agent.mdx, apps/docs/docs/guides/agents/4_agentic_rag.mdx, examples/contextAwareAgent.js, packages/core/src/agent/index.ts, packages/llamaindex/src/agent/anthropic.ts, packages/llamaindex/src/agent/contextAwareMixin.ts, packages/llamaindex/src/agent/index.ts, packages/llamaindex/src/agent/openai.ts
This PR introduces context-awareness functionality for agents, inspired by the discussion in #1224.
- Added `withContextAwareness` mixin in `contextAwareMixin.ts`
- Created `OpenAIContextAwareAgent` and `AnthropicContextAwareAgent`
- Updated relevant documentation and examples
The goal is to allow agents to access indexed data without explicitly calling retriever tools, reducing latency in real-time scenarios especially with not so fast LMs. This approach is analogous to the ContextChatEngine, which automatically incorporates retriever data into the chat context.
The implementation uses a mixin pattern to add context retrieval and injection capabilities to existing agent classes. This method allows for flexibility and easy extension to different agent types.
Feedback on the implementation …
=> Implement context-aware agent functionality.

apps/next/src/content/docs/llamaindex/loading/meta.json, apps/next/src/content/docs/llamaindex/loading/node-parser.mdx, packages/core/postprocessor/package.json, packages/core/src/embeddings/base.ts, packages/core/src/node-parser/base.ts, packages/core/src/schema/node.ts, packages/core/src/schema/type.ts, packages/llamaindex/e2e/fixtures/llm/openai.ts, packages/node-parser/code/package.json, packages/node-parser/html/package.json, packages/node-parser/package.json, packages/node-parser/src/code/index.ts, packages/node-parser/src/html/index.ts, packages/node-parser/tsconfig.json, packages/node-parser/turbo.json, pnpm-lock.yaml, tsconfig.json, unit/node-parser/code.test.ts, unit/node-parser/html.test.ts, unit/package.json
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1122
```shell
pnpm add @llamaindex/node-parser
```
```shell
pnpm add tree-sitter tree-sitter-javascript
```
```shell
pnpm add web-tree-sitter tree-sitter-javascript
```
```ts
import Parser from "tree-sitter";
import JS from "tree-sitter-javascript";
import TS from "tree-sitter-typescript";
const parser = new Parser();
parser.setLanguage(JS);
parser.setLanguage(TS.typescript);
const codeSplitter = new CodeSplitter({
maxChars: "const a = 1;".length,
getParser: () => parser,
});
```
=> feat: add code splitter and html node parser

.changeset/metal-cameras-argue.md, examples/cosmosdb/addPlainData.ts, examples/cosmosdb/loadVectorData.ts, examples/cosmosdb/queryVectorData.ts, examples/data/shortStories.json, examples/package.json, packages/llamaindex/package.json, packages/llamaindex/src/readers/SimpleCosmosDBReader.ts, packages/llamaindex/src/readers/index.ts, packages/llamaindex/src/vector-store/AzureCosmosDBNoSqlVectorStore.ts, packages/llamaindex/src/vector-store/index.ts, packages/llamaindex/tests/mocks/TestableAzureCosmosDBNoSqlVectorStore.ts, packages/llamaindex/tests/package.json, packages/llamaindex/tests/readers/SimpleCosmosDBReader.test.ts, packages/llamaindex/tests/utility/mockCosmosClient.ts, packages/llamaindex/tests/vector-stores/AzureCosmosDBNoSqlVectorStore.int.test.ts, packages/llamaindex/tests/vector-stores/AzureCosmosDBNoSqlVectorStore.test.ts, packages/readers/cosmosdb/package.json, packages/readers/package.json, packages/readers/src/cosmosdb.ts, pnpm-lock.yaml, unit/package.json, unit/readers/SimpleCosmosDBReader.test.ts
This PR makes following changes to the project:
- Add support for using Azure Cosmos DB NoSQL API as a vector-store.
- Add a simple Cosmos DB reader to read the data from the Cosmos DB.
- Add a shortStories JSON dataset.
- Add CosmosDBNoSqlVectorStore RAG example.
=> feat: add `AzureCosmosDBNoSqlVectorStore` and `SimpleCosmosDBReader`

packages/core/src/agent/base.ts, packages/core/src/agent/llm.ts, packages/core/src/agent/types.ts, packages/core/src/chat-engine/base.ts, packages/providers/anthropic/src/agent.ts, packages/providers/ollama/src/agent.ts, packages/providers/openai/package.json, packages/providers/openai/src/agent.ts, pnpm-lock.yaml
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1411
This is a small API addition but did lot of typing on our codebase.
There're some roadmap for the agent:
1. Use workflow to refactor the agent
2. `chatOptions` should be normalized for all llm related stuff, like chat engine, agent...
=> feat: allow `tool_choice` for OpenAIAgent

.changeset/witty-worms-marry.md, packages/core/src/memory/base.ts, packages/core/src/storage/chat-store/base-chat-store.ts
This PR adds async support to BaseChatStore and BaseChatStoreMemory.
Issue link: https://github.com/run-llama/LlamaIndexTS/issues/1469
Continuation of PR: https://github.com/run-llama/LlamaIndexTS/pull/1470
=> feat: add async support to BaseChatStore and BaseChatStoreMemory

.changeset/cuddly-geckos-clap.md, packages/llamaindex/src/vector-store/PGVectorStore.ts
As described in https://github.com/run-llama/LlamaIndexTS/issues/1508
Inside a Server Action deployed on Vercel, the check done in the constructor of PGVectorStore fails to identify the vercel/posgres pool used.
In this change, I propose to check the presence or absence of some methods.
(Note that the methods also will be bond)
```ts
if (
config.client.constructor.name.includes("Vercel") ||
(!!(config.client as VercelPool).connect &&
!!(config.client as VercelPool).query &&
!(config.client as Sql).unsafe)
)
```
=> fix: supports vercel bundling

.changeset/good-ants-fix.md, .github/workflows/test.yml, e2e/node/embedding/clip.e2e.ts, packages/env/src/internal/multi-model/node.ts, packages/llamaindex/package.json, packages/workflow/package.json, packages/workflow/src/workflow-context.ts, packages/workflow/tsconfig.json, pnpm-lock.yaml
Upstream issue: https://github.com/stackblitz/webcontainer-core/issues/560
=> fix: allow Node 18 again to make Stackblitz work

.changeset/weak-cats-smash.md, packages/llamaindex/src/next.ts
Passes through the `options` parameter when calling the `userWebpack` to support existing NextJS configs that rely on those options being passed through.
I ran into this issue when attempting to setup Langtrace in my NextJS app. Their recommended adjustment to the NextJS config relied on the webpack `options.isServer`. That's when I noticed this was a bug. Instead of trying to work around, I figured I would submit a quick fix.
From: https://docs.langtrace.ai/supported-integrations/web-frameworks/nextjs
```js
import { ModuleAlias } from '@langtrase/typescript-sdk/dist/webpack/plugins/ModuleAlias.js'
const nextConfig = {
webpack: (config, { isServer }) => {
if (isServer) {
config.resolve.plugins = [
...(config.resolve.plugins || []),
new ModuleAlias(process.cwd())
]; …
```
=> Pass options through to userWebpack in withLlamaIndex

.changeset/olive-foxes-watch.md, apps/next/src/content/docs/llamaindex/guide/agents/1_setup.mdx, apps/next/src/content/docs/llamaindex/guide/agents/2_create_agent.mdx, apps/next/src/content/docs/llamaindex/guide/agents/3_local_model.mdx, apps/next/src/content/docs/llamaindex/guide/agents/4_agentic_rag.mdx, apps/next/src/content/docs/llamaindex/guide/agents/5_rag_and_tools.mdx, apps/next/src/content/docs/llamaindex/guide/agents/6_llamaparse.mdx, apps/next/src/content/docs/llamaindex/guide/agents/7_qdrant.mdx
When you are on the Agent tutorial the link leads to the 500 page because the name of the files didn't match. They have to have the number of the chapter prefix
**Steps to reproduce:**
- Got to: [https://ts.llamaindex.ai/docs/llamaindex/guide/agents/5_rag_and_tools](https://ts.llamaindex.ai/docs/llamaindex/guide/agents/5_rag_and_tools)
- scroll down and try to redirect to Llamaparse from this link
> Great! Now let's improve accuracy by improving our parsing with [LlamaParse](https://ts.llamaindex.ai/docs/llamaindex/guide/agents/llamaparse).
**Actual result:**
500 error page
**Expected result:**
You are redirected to [https://ts.llamaindex.ai/docs/llamaindex/guide/agents/6_llamaparse](https://ts.llamaindex.ai/docs/llamaindex/guide/agents/6_llamaparse)
There are a few places in the …
=> fix: doc links

.changeset/smooth-shirts-shop.md, packages/providers/openai/src/llm.ts
This is a follow up from the previous fix.
The previous fix stopped working for an unknown reason but this one for sure fixes the issue @marcusschiesser
=> fix: delete temp competely from params when calling openai o3

.changeset/itchy-tips-reflect.md, examples/gemini/agent.ts, packages/providers/google/src/types.ts, packages/providers/google/src/utils.ts
Error: Content with role 'user' can't contain 'functionResponse' part
Chat History when debugging:
```
const chatHistory = [
{ role: "user", parts: [{ text: "How much is 5 + 5? then divide by 2" }] },
{ role: "model", parts: [{ functionCall: { name: "sumNumbers", args: { a: 5, b: 5 } } }] },
{ role: "user", parts: [{ functionResponse: { name: "sumNumbers", response: { result: "10" } } }] },
{ role: "model", parts: [{ functionCall: { name: "divideNumbers", args: { a: 10, b: 2 } } }] }
];
```
VALID_PARTS_PER_ROLE from @google/generative-ai package
https://github.com/google-gemini/generative-ai-js/blob/2df2af03bb07dcda23b07af1a7135a8b461ae64e/src/methods/chat-session-helpers.ts#L34
```
const VALID_PARTS_PER_ROLE = {
user: ["text", "inlineData"],
function: ["functionResponse"],
model: …
```
=> fix(gemini): use function role for message contains tool-result

e2e/node/smoke.e2e.ts, examples/package.json, package.json, packages/core/src/vector-store/index.ts, patches/bunchee@6.3.4.patch, pnpm-lock.yaml
Upstream: https://github.com/huozhi/bunchee/pull/657
=> fix: cjs module resolve esm module unexpectedly

.changeset/young-pans-pump.md, packages/llamaindex/src/cloud/utils.ts
Try creating LlamaCloud with an invalid API key:
```
import { LlamaCloudIndex } from "llamaindex";
const index = new LlamaCloudIndex({
name: "test",
projectName: "Default",
baseUrl: process.env.LLAMA_CLOUD_BASE_URL,
apiKey: process.env.LLAMA_CLOUD_API_KEY,
});
await index.ensureIndex({ verbose: true });
```
I got this unclear error message:
```
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
code: 'ERR_UNHANDLED_REJECTION'
}
Node.js v20.9.0
```
After fixing:
``` …
```
=> fix: enhance error message in llamacloud

.changeset/fix_refine_synthesizer_empty_source_nodes_behavior.md, packages/core/src/response-synthesizers/factory.ts, packages/core/tests/memory/chat-memory-buffer.test.ts, packages/core/tests/response-synthesizers/compact-and-refine.test.ts
Previously, if you passed an empty array of source nodes to the Refine response synthesizer `getResponse` method. it would end up throwing an internal error because `response` would be left as undefined. When that was passed to `streamConverter` it would then throw an error in the `for await` loop.
I experienced this intermittent in my development environment or when testing with no data, and it's possible someone could experience this, so I wanted to have the behavior defined rather than throw an error. 
The new behavior is that it defaults the response string to `""` if sourceNodes is provided as an empty array.
=> Fix refine synthesizer empty source nodes behavior

.changeset/selfish-kids-own.md, packages/core/src/node-parser/base.ts, packages/core/src/node-parser/markdown.ts, packages/core/src/node-parser/sentence-window.ts, packages/core/src/utils/index.ts, packages/core/tests/node-parser/node-parser.test.ts, packages/llamaindex/src/indices/keyword/index.ts, packages/llamaindex/src/indices/summary/index.ts
Semantic chunking will requires llm embedding whichi need async function call
Related: https://github.com/run-llama/LlamaIndexTS/issues/1636
=> feat(node-parser): support async function

.changeset/red-taxis-hope.md, packages/providers/voyage-ai/tsconfig.json, tsconfig.json
Fixing tsconfigs for the new Voyage.ai provider (see #1574). Should also fix broken link to the class documentation in the docs.
=> fix: Voyage typescript configs + docs

.changeset/cyan-eggs-fail.md, packages/workflow/src/agent/function-agent.ts
Ollama uses a partial toolCall, which means that the toolCall option only appears in a chunk.
=> fix agent workflow tool call for Ollama

.changeset/rude-gifts-leave.md, packages/providers/storage/azure/src/chatStore/AzureCosmosMongovCoreChatStore.ts, packages/providers/storage/azure/src/docStore/AzureCosmosMongovCoreDocumentStore.ts, packages/providers/storage/azure/src/indexStore/AzureCosmosMongovCoreIndexStore.ts
Add fromConnectionString  to:
- AzureCosmosVCoreIndexStore
- AzureCosmosVCoreDocumentStore
- AzureCosmosVCoreChatStore
Add UA in order to track the usage of vCore
=> fix: Add fromConnectionString method for Azure vCore storages

apps/next/src/app/docs/[[...slug]]/page.tsx, apps/next/src/components/type-table.ts
Fix issue #1732 
Root Cause:
AutoTypeTable cannot load tsconfig.json when the page is not found.
See: https://fumadocs.vercel.app/docs/ui/components/auto-type-table#deep-dive
Solution: use AutoTypeTable only when the page is found
=> fix: unhandled server error when accessing not found pages

.changeset/cuddly-bulldogs-drive.md, packages/core/src/chat-engine/context-chat-engine.ts
This was the root cause of the GoogleStudio failing to generate images.
=> fix: context engine additional options not being passed

apps/next/src/content/docs/llamaindex/modules/data_stores/vector_stores/qdrant.mdx
when trying to user Quadrant vector store I was having issues with the configuration. The error I got was:
```
Object literal may only specify known properties, but 'vectorStore' does not exist in type 'VectorIndexOptions & { docStoreStrategy?: DocStoreStrategy | undefined; }'. Did you mean to write 'vectorStores'?ts(2561) 
```
The way I was able to fix it is:
```
const vectorStore = new QdrantVectorStore({
url: "http://localhost:6333",
});
await VectorStoreIndex.fromDocuments(documents, {
vectorStores: { TEXT: vectorStore },
});
Please check this PR.
=> Update qdrant.mdx documentation

.changeset/purple-gifts-decide.md, apps/next/src/content/docs/llamaindex/integration/vercel.mdx, packages/providers/vercel/package.json, packages/providers/vercel/src/tool.ts, packages/providers/vercel/tests/index.test.ts, pnpm-lock.yaml
I want to be able to access source nodes from the tool call with the Vercel integration:
```ts
import { LlamaCloudIndex } from "@llamaindex/cloud";
// Create a LlamaCloud index
const index = await LlamaCloudIndex.fromDocuments({
documents: [document],
name: "your-index-name",
projectName: "your-project",
apiKey: process.env.LLAMA_CLOUD_API_KEY,
});
// Use it the same way as VectorStoreIndex
const queryTool = llamaindex({
model: openai("gpt-4"),
index,
description: "Search through the documents",
options: { fields: ["sourceNodes", "messages"]} // get messages and sourceNodes
});
// Use the tool with Vercel's AI SDK
streamText({
model: openai("gpt-4"),
prompt: "Your question here",
tools: { queryTool },
}).toDataStream();
```
=> feat: vercel tool response fields options

.changeset/young-countries-exercise.md, examples/agent/mcp_tools.ts, packages/tools/package.json, packages/tools/src/index.ts, packages/tools/src/tools/mcp.ts, packages/tools/tests/mcp.test.ts, pnpm-lock.yaml
- Introduced MCP client functionality in the tools package, allowing interaction with the Model Context Protocol.
- Added a new example script demonstrating the use of MCP tools to list files in a directory.
- Updated package dependencies to include @modelcontextprotocol/sdk version 1.8.0.
- Created tests for MCP tools to ensure proper functionality and tool listing.
For: https://github.com/run-llama/LlamaIndexTS/issues/1817
=> feat: add MCP tools integration and example usage

.changeset/yellow-carpets-return.md, examples/anthropic/thinking.ts, packages/providers/anthropic/src/llm.ts, packages/providers/anthropic/tests/index.test.ts
This adds the `thinking` messages and their signatures (`thinking_signature`) to the `options` field when `stream` is `false`, and also adds `thinking_signature` to `options` when `stream` is `true`, 
- I noticed the code at https://github.com/run-llama/LlamaIndexTS/blob/main/examples/anthropic/thinking.ts returns `thinking` in `options`, but no `signature` for the `thinking` messages was being returned
- I noticed that making `stream: false` wasn't returning `thinking` nor `thinking_signature` in `option`, so I added them both
- Since now the user may add the returned messages to the history, I changed `formatMessages` to handle the new keys in `options`, so that Anthropic receives the expected format
I added tests to make sure `thinking` is correctly converted and to make sure it comes …
=> Add "thinking" and "thinking_signature" to chat response, and "thinking_signature" to chat stream

.changeset/silver-taxis-call.md, apps/next/src/content/docs/llamaindex/modules/data/stores/vector_stores/qdrant.mdx, examples/storage/qdrantdb/README.md, examples/storage/qdrantdb/searchParams.ts, packages/core/src/retriever/index.ts, packages/core/src/vector-store/index.ts, packages/llamaindex/src/indices/vectorStore/index.ts, packages/providers/storage/qdrant/src/QdrantVectorStore.ts, packages/providers/storage/qdrant/tests/QdrantVectorStore.test.ts
This PR adds functionality to allow users to pass additional search params when using the `query` method of `QdrantVectorStore`.
- Add `qdrant_search_params` as options when using the `query` method in `QdrantVectorStore`. 
- Update implementation of vector store and vector index to allow for search params.
- Create an example that uses search params when querying a `Qdrant` vector store.
- Tests incorporating search params.
- Typo in `Qdrant` example readme.
- Add a line in `docs` to mention setting search parameters.
closes #1910
=> feat: qdrant search params

.changeset/lazy-books-stand.md, packages/providers/storage/azure/src/vectorStore/AzureCosmosDBMongoVectorStore.ts
Add Vector Index Compression support for Azure Cosmos DB Mongo vector store: 
- Product Quantization: https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/product-quantization
- Half-Precision: https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/half-precision
=> feat: Add vector index compression for  AzureCosmosDBMongoDBVectorStore

.changeset/green-worlds-rule.md, packages/providers/google/src/studio/index.ts
Gemini was returning empty parts consecutively before a tool call, most likely because it was accumulating itself and yielding empty parts
That caused tool calls failing in agent, this fixes the issue
=>  fix: ignore empty parts for gemini which confuses agent

.changeset/crazy-heads-invite.md, apps/next/src/app/(home)/page.tsx
**Description**
This PR corrects the import path for SimpleDirectoryReader on the main documentation landing page. The previous import statement was incorrect and appeared prominently in the official documentation, which could easily confuse users who are using the library for the first time. By updating this, we ensure that newcomers have a clear and accurate starting point.
**Changes Made**
- Updated the import statement in `apps/next/src/app/(home)/page.tsx`.
- Changed from:
```typescript
import { SimpleDirectoryReader, VectorStoreIndex } from "llamaindex";
```
- To:
```typescript
import { VectorStoreIndex } from "llamaindex";
import { SimpleDirectoryReader } from "@llamaindex/readers/directory";
```
**Why**
`SimpleDirectoryReader` is defined in …
=> fix: correct SimpleDirectoryReader import path

.changeset/stupid-boats-leave.md, packages/core/src/node-parser/utils.ts
This PR tries to reduce the issues related to https://github.com/run-llama/LlamaIndexTS/issues/2019
It won't fix all the issues, but it should improve a bit the default performance
=> Add more Acronyms on SentenceSplitter

.changeset/sixty-wasps-flow.md, packages/core/src/memory/factories.ts, packages/core/tests/memory/memory.test.ts
The `createMemory` factory function was not correctly passing options to the underlying `Memory` object
This meant that the docs example doesn't actually work
https://ts.llamaindex.ai/docs/llamaindex/modules/data/memory
=> fix memory factory

.changeset/slimy-dingos-notice.md, examples/README.md, examples/agents/workflow/joke.ts, examples/package.json, pnpm-lock.yaml
This was breaking stackblitz examples
Also took the time to update the README to be more useful for when we drop users into stackblitz
=> remove workspace from examples package.json

.changeset/tough-hoops-smash.md, packages/providers/anthropic/src/llm.ts
Stream partial calls. For context, this is already implemented for the openai provider.
See #1840
=> feat(anthropic): stream partial tool calls

.changeset/thirty-terms-rush.md, examples/models/openai/responses/image-gen.ts, examples/models/openai/responses/multi-turn-image-gen.ts, packages/providers/openai/src/responses.ts, packages/providers/openai/src/utils.ts
#1974
- Added `image_id` parameter to image generation tools for multi-turn support
- Enhanced response parsing to extract and store `image_id` from OpenAI responses  
- Updated message options with `OpenAIResponsesMessageOptions` type including `image_id` field
- Implemented tool configuration to pass `image_id` in subsequent requests for image modifications
- Created example demonstrating multi-turn image generation workflow with initial and modified images
=> feat: multi-turn image generation support

.changeset/brave-snakes-grin.md, packages/workflow/src/agent/agent-workflow.ts, packages/workflow/test/agent-workflow.test.ts
Changes as suggested in #2071 
Additionally, simplified the intialization of the logger object. The logic should be equivalent since `this.verbose` is set in a line above.
```ts
//from
this.logger =
verbose === false
? emptyLogger
: verbose || this.verbose
? consoleLogger
: emptyLogger;
//to
this.logger = logger ?? (this.verbose ? consoleLogger : emptyLogger);
```
=> chore: add logger as param to AgentWorkflow constructor

apps/next/src/content/docs/llamaindex/modules/models/llms/bedrock.mdx
Changed @llamaindex/community to @llamaindex/aws, and updated model and inference models list. For #2124
**Question**: are the comments for the meta models and claude 3 opus still valid? Not sure what "only available via inference endpoints (see below)" means.
=> docs: updated bedrock import and supported models

.changeset/two-pigs-deliver.md, packages/providers/deepseek/src/llm.ts
Fixes issue #2147 by adding 'as const' to deepseek models to ensure proper TypeScript compilation. Previously would lead to failing to build context window sizes.
To test, build the deepseek provider and ensure that the `.ts` dist files build with the correct context window sizes.
> Closes #2147
=> fix(deepseek): add 'as const' assertion to DEEPSEEK_MODELS for correct TypeScript inference

.changeset/ninety-pens-attend.md, apps/next/src/content/docs/llamaindex/tutorials/structured_data_extraction.mdx, examples/agents/tools/response-format-exec.ts, packages/core/src/llms/base.ts, packages/core/src/llms/utils.ts, packages/core/src/tools/function-tool.ts
With this PR we add `responseFormat` to `llm.exec` to have a way of generating structured output responses with a tool call
=> feat: add responseFormat to llm.exec

.changeset/silent-vans-melt.md, packages/providers/openai/src/llm.ts, packages/providers/openai/src/utils.ts
This adds the `minimal` reasoningEffort supported by gpt-5 family.
Fixes #2176
=> chore: add minimal reasoning effort for gpt5

.changeset/purple-icons-buy.md, packages/providers/google/src/constants.ts
Adds latest stabel 2.5 models from: https://ai.google.dev/gemini-api/docs/models
=> chore: add latest google models

.changeset/light-spiders-pump.md, packages/providers/anthropic/src/llm.ts
fixes:   #2182
**Problem:**
Setting `temperature: 0` in Anthropic LLM constructor was incorrectly defaulting to `1` instead of preserving the `0` value.
**Root Cause:**
The nullish coalescing operator (`??`) in the constructor was not properly handling the case where temperature is explicitly set to `0`.
**Solution:**
Changed the temperature initialization logic from:
```typescript
this.temperature = init?.temperature ?? 1;
```
To:
```typescript
this.temperature = init?.temperature != null ? init.temperature : 1;
```
**Impact:**
-  Temperature `0` now works correctly for deterministic responses
- All other valid temperature values (0.1, 0.5, etc.) are preserved
- Invalid/null values still default to `1`
-  No breaking changes to existing functionality
=> fix: anthropic temperature parameter not respecting value 0
